### ISSUE TITLE
Error in "get_nearest_centerline" (argoverse.map_representation.map_api)

### ISSUE THREAD

**Issue by pskugit** [argoai/argoverse-api#100]
The function to retrieve the nearest centerline should double the search radius in case no lanes where found.

```
while True:
    nearby_lane_ids = self.get_lane_ids_in_xy_bbox(
        query_x, query_y, city_name, query_search_range_manhattan=search_radius
    )
    if nearby_lane_ids is None:
        search_radius *= 2  # double search radius
    else:
        break
```

However, since get_lane_ids_in_xy_bbox returns an empty list ([ ]) and not None, this search radius increase is never executed. 

suggestion:
```
while True:
    nearby_lane_ids = self.get_lane_ids_in_xy_bbox(
        query_x, query_y, city_name, query_search_range_manhattan=search_radius
    )
    if not nearby_lane_ids:
        search_radius *= 2  # double search radius
    else:
        break
```

(Also, sorry if this has been fixed already or in case I got it wrong)

**Comment by johnwlambert** [comment]
Hi @pskugit thanks for catching this, you are absolutely right. Would you mind making a pull request with that change and we'll merge it in?

**Comment by pskugit** [comment]
Done.
