### ISSUE TITLE
Synchronizing lidar with stereo images

### ISSUE THREAD

**Issue by swdev1202** [argoai/argoverse-api#101]
I am trying to synchronize lidar point cloud files to the stereo images.
Since stereo cameras have a lower frequency (@ 5Hz) than the LiDAR (@ 10 Hz), I wanted to use a 'stereo_front_left' image timestamp to obtain the closest lidar timestamp using this function [get_closest_lidar_timestamp](https://github.com/argoai/argoverse-api/blob/652bb500eafd2b21a8a346a3b762c1114f4c314a/argoverse/data_loading/synchronization_database.py#L119). However, I get some stereo images having a bigger timestamp difference than the threshold (`MAX_LIDAR_ANYCAM_TIMESTAMP_DIFF`), causing an error and aborts execution.

I saw a similar post on having an error when there is a bigger difference on a timestamp when synchronizing lidar timestamp to the cam images (Issue #49 & #53). Can we change the error handling to give just warnings so I can skip on the images that are far off the lidar threshold?

If you have any other ideas to synchronize lidar scans to the stereo images, please let me know!

Thank you :)

**Comment by janesjanes** [comment]
Thanks for letting us know! The error issue should be fixed now in https://github.com/argoai/argoverse-api/pull/102

But the function and threshold isn't for stereo, though. We don't currently have a separated function for stereo, but you can simply switch to using `MAX_LIDAR_STEREO_CAM_TIMESTAMP_DIFF ` instead in the `get_closest_lidar_timestamp`.

**Comment by swdev1202** [comment]
Thank you @janesjanes for letting me know `get_closest_lidar_timestamp` is only for ring cameras.
I will try with `MAX_LIDAR_STEREO_CAM_TIMESTAMP_DIFF`.
