### ISSUE TITLE
Drivable area as a closed polygon

### ISSUE THREAD

**Issue by Elbek1997** [argoai/argoverse-api#104]
I am using argoverse Forecasting dataset and Map api.

I want to make BEV(Birds eye view) rasterized map image. For this image I need to fill drivable area in a different color.

I am using Map function [find_local_driveable_areas](https://github.com/argoai/argoverse-api/blob/95a5d340acd6a7d8cdea4b7b38b29729c3508332/argoverse/map_representation/map_api.py#L993). But this function returns just contours of drivable area.

Is there any other functions that returns closed polygon(s) for given xy bounding box?

**Comment by alliecc** [comment]
Hi Elbek1997, thanks for your question!

We don't have a function that returns closed polygons in this version of Argoverse api. The drivable area is stored in rasterized format, so maybe one solution is to find all the drivable grid map points inside your BEV view and compute contour from that. Please see this function for loading rasterized map: https://github.com/argoai/argoverse-api/blob/95a5d340acd6a7d8cdea4b7b38b29729c3508332/argoverse/map_representation/map_api.py#L162

Hope this helps!

**Comment by johnwlambert** [comment]
@Elbek1997 , thanks very much for your interest in our work.

As Allie noted, we store the drivable area as a rasterized binary segmentation (2d grid). You can [access it](https://github.com/argoai/argoverse-api/blob/95a5d340acd6a7d8cdea4b7b38b29729c3508332/argoverse/map_representation/map_api.py#L414) with a point cloud meshgrid to get the different color you desire as follows:

```python
from argoverse.utils.mesh_grid import get_mesh_grid_as_point_cloud

avm = ArgoverseMap()
pts = get_mesh_grid_as_point_cloud(min_x, max_x, min_y, max_y)
pt_labels = avm.get_raster_layer_points_boolean(pts, city_name, layer_name = 'driveable_area')
drivable_area_mask = np.zeros((max_y - min_y + 1, max_x - min_x + 1), dtype=np.uint8)
# index into 2-d grid at (y,x)
drivable_area_mask[ pts[:,1], pts[:,0] ] = pt_labels
```

and then color any image with this binary mask as follows:
```python
def vis_mask(img: np.ndarray, mask: np.ndarray, col: Tuple[int,int,int], alpha: float=0.4):
	"""
	Visualizes a single binary mask by coloring the region inside a binary mask
	as a specific color, and then blending it with an RGB image.

		Args:
		-	img: Numpy array, representing RGB image with values in the [0,255] range
		-	mask: Numpy integer array, with values in [0,1] representing mask region
		-	col: color, tuple of integers in [0,255] representing RGB values
		-	alpha: blending coefficient (higher alpha shows more of mask,
				lower alpha preserves original image)

		Returns:
		-	image: Numpy array, representing an RGB image, representing a blended image
				of original RGB image and specified colors in mask region.
	"""
	img = img.astype(np.float32)
	idx = np.nonzero(mask)

	img[idx[0], idx[1], :] *= 1.0 - alpha
	img[idx[0], idx[1], :] += alpha * col

	return img.astype(np.uint8)
```

**Comment by Elbek1997** [comment]
Thanks @alliecc and @johnwlambert  for help

**Comment by quan-dao** [comment]
Hello,
Here is my notebook to convert local driveables area into binary image: https://gist.github.com/quan-dao/197aab1ad06b70abfa9f53adb30e8e18
