### ISSUE TITLE
Question about the bounding box

### ISSUE THREAD

**Issue by leezonpen** [argoai/argoverse-api#105]
Hello,

I found that the height of a bounding box for a LARGE VEHICLE class was incorrect. The information of this annotations is follow:
log_id: 043aeba7-14e5-3cde-8a5c-639389b6d3a6
timestamp: 315967467019819000
track_label_uuid: e1af29a9-c15b-4291-8dc6-3e38c17e2257

I also observe that a VEHICLE class annotation was not include all the points of the object in the same frame (track_label_uuid: c63322f6-a906-4286-b1e0-dc32bece0a37). 

I use the Argoverse v1.1 and extract pointcloud and label with the `get_lidar(idx)` and `get_label_object(idx)`. I am just getting start to process the data and don't check all frames.

Any answer will be appreciated.

**Comment by alliecc** [comment]
Hi @leezonpen, 
Thanks for your interest in Argoverse! 
We have confirmed the issues you mentioned and we will keep this in mind for future updates.
