### ISSUE TITLE
Measure of following lane centerline

### ISSUE THREAD

**Issue by Elbek1997** [argoai/argoverse-api#106]
I was using argoverse dataset forecasting dataset for vehicle trajectory prediction. As a constraint or environment data I am using nearby centerlines.

I need to find more relevant centerlines. Filtering by just euclidean distance or direction of centerline didn't help much. 

Is there any function or algorithm you can suggest to measure between centerline and trajectory where trajectory kind of follows given centerline ?

**Comment by jagjeet-singh** [comment]
Hi @Elbek1997 
Thanks for your interest in Argoverse. Apologies for the delayed reply.
The problem you pointed out is indeed a very challenging one. It's hard to come up with the relevant set of centerlines that would fit all the edge cases. 
If you haven't already seen this, there is a relevant function in the api here:
https://github.com/argoai/argoverse-api/blob/0219dd88ac1a63ead0ff4a346ce1de30296be65e/argoverse/map_representation/map_api.py#L788 
There is also a different version of this function released with the baselines here:
https://github.com/jagjeet-singh/argoverse-forecasting/blob/ba60688edf5770738d06d2a8472425dd3d60b049/utils/map_features_utils.py#L159
Hope it helps!

**Comment by johnwlambert** [comment]
This is a hard problem, fundamentally. Some trajectories cross over a number of centerlines, especially around intersections. Some heuristics are possible e.g. one could use a RANSAC-like approach (hypothesize and verify) -- hypothesize trajectories by caching paths during DFS from closest lane IDs, then do point-in-polygon tests within the hallucinated trajectory polygons (concatenated lane polygons). A maximum amount of trajectory path waypoints falling into such a path would be a vote of highest confidence. A learning-based approach would certainly be more favorable than such heuristics -- one could learn which features are most suitable for correspondence (e.g. registration of trajectory to graph).
