### ISSUE TITLE
coordinate for images

### ISSUE THREAD

**Issue by mengzhibin** [argoai/argoverse-api#114]
We need images with coordinate such as gps, but I cannot understand the converting function of your api. Is there such dataset?

**Comment by janesjanes** [comment]
Hey mengzhibin,
this might help answering your question https://github.com/argoai/argoverse-api/issues/95 

We don't currently have gps in the dataset but you can convert to that pretty easily. The city coordinate we are using is based on UTM system. 

_"City coordinates can be converted to the UTM (Universal Transverse Mercator) coordinate system by simply adding the city’s origin in UTM coordinates to the object’s city coordinate pose"_

Then you can just convert from UTM to lat/long

**Comment by johnwlambert** [comment]
Thanks for your interest in our work @mengzhibin. As @janesjanes said, the real conversion here is from UTM to GPS: our city coordinate system origin is simply a constant offset from UTM. In the Supplemental Material we refer to the following paper for the math:
J. P. Snyder. Map projections: A working manual. u.s. geological survey professional paper. page 61, 1987.
https://pubs.usgs.gov/pp/1395/report.pdf
pages 57-64

We don't provide a UTM->GPS converter in our API, but there are many other python packages that do.

**Comment by mengzhibin** [comment]
Thanks for your reply

**Comment by lavorue** [comment]
Dear @janesjanes @johnwlambert, where can I find the city origin in UTM, i.e. the offset that I would need to add to the city coordinates? So far, I could not find any information about that in the argoverse data or map files.
