### ISSUE TITLE
Lidar Rings

### ISSUE THREAD

**Issue by Kartik17** [argoai/argoverse-api#116]
I noticed that since the point cloud data was collected by two lidars mounted on top of each other each having its individual 32 rings, wouldn't that mean there are 64 rings (The closer rings of the two lidars might overlap but the rings which are formed farther away won't)?

**Comment by James-Hays** [comment]
Hi Kartik,

Yes, Argoverse generally aggregates points from both LiDARs and treats it like a 64 beam LiDAR.

**Comment by Kartik17** [comment]
Thanks, I was in the process of converting the point cloud to a spherical image(Height: Elevation Angle, Width: Azimuthal Angle). But got confused seeing that in the data the point cloud rings are labelled from 1 to 32 only, whereas it should behave like a 64  beam lidar.

**Comment by janesjanes** [comment]
Hey Kartik,
The labels you are seeing is the original index from each of the lidar, so there are only between 1 and 32. We only aggregate points and not the index label.

If you want to separate points from top/bottom lidars, there's also [this repo](https://github.com/irenecortes/argoverse_lidar)

Also related https://github.com/argoai/argoverse-api/issues/37 https://github.com/argoai/argoverse-api/issues/20

**Comment by Kartik17** [comment]
Actually I found an interesting pattern when I plotted the Azimuthal angle of a point cloud file without disturbing the order of points. From this, it seems one can manually separate the two lidar points just by a partition formed at the midpoint( or at the point at which azimuthal sharply decreases.)

![image](https://user-images.githubusercontent.com/32801164/78970197-bf579700-7ad6-11ea-90bf-7e8181ef8864.png)
