### ISSUE TITLE
demo_usage: argoverse tracking tutorial issue

### ISSUE THREAD

**Issue by v-venkatesan** [argoai/argoverse-api#123]
![Screen Shot 2020-04-23 at 4 04 23 PM](https://user-images.githubusercontent.com/16858887/80158095-83174280-857c-11ea-8e67-9f91bc031601.png)

I was getting started with the tracking tutorial and i encountered this error. I would appreciate if somebody help me figure why this error occurs.

**Comment by alliecc** [comment]
Did you run the line "import argoverse.visualization.visualization_utils as viz_util" ?

**Comment by v-venkatesan** [comment]
I did and my bad, it was a typo. viz_util became viz_until. Thank you so much anyway.
