### ISSUE TITLE
Forecasting Testset Maps

### ISSUE THREAD

**Issue by os1a** [argoai/argoverse-api#125]
Hi,
I would like to ask something regarding the testing split of the forecasting dataset. According to the utils functions provided, you can get a subsection of the map (lanes) by filtering only those lying within all trajectories for 5 seconds.

However, the testing split provides the trajectories for only 2 seconds. When generating the map section containing these trajectories, would it still contain the future trajectories?

Assuming we have access to the true future trajectories for the testing split, can we draw these trajectories on the map created from the observation trajectories only (for 2 seconds).

**Comment by janesjanes** [comment]
Hi @os1a ,
I'm not really sure what are you referring to, can you point me to that util function? 

If you generate the submap for the 2 seconds trajectories, and then plot it with the full 5 seconds trajectories, then it's likely to miss some part of the map. You can query for any location on the map, though, not just the provided 2 seconds. The map we provided contains all full trajectories, so if you have some heuristic on where the trajectories could go, you can query based on that.

**Comment by johnwlambert** [comment]
Hi @os1a, closing this issue for now. Feel free to re-open if you have further questions.
