### ISSUE TITLE
AssertionError: No nearby lanes found!! on argoverse_forecasting_tutorial.ipynb

### ISSUE THREAD

**Issue by lawchekun** [argoai/argoverse-api#126]
Hi, I'm getting the following issue on the `argoverse_forecasting_tutorial.ipynb`

This particular code block to be specific,  the earlier code segment `Visualizing sequences` works for me, so I don't think it is a path issue. Please advise?

```
from argoverse.map_representation.map_api import ArgoverseMap

avm = ArgoverseMap()

obs_len = 20

seq_path = f"{root_dir}/2645.csv"
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[1].city, viz=True)

seq_path = f"{root_dir}/3828.csv"
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[4].city, viz=True)
```

```
AssertionError                            Traceback (most recent call last)
<ipython-input-18-6001c862e180> in <module>
     13 seq_path = f"{root_dir}/3828.csv"
     14 agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
---> 15 candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[4].city, viz=True)

~/argoverse-api/argoverse/map_representation/map_api.py in get_candidate_centerlines_for_traj(self, xy, city_name, viz, max_search_radius)
    814             curr_lane_candidates = self.get_lane_ids_in_xy_bbox(xy[-1, 0], xy[-1, 1], city_name, manhattan_threshold)
    815 
--> 816         assert len(curr_lane_candidates) > 0, "No nearby lanes found!!"
    817 
    818         # Set dfs threshold

AssertionError: No nearby lanes found!!
```

**Comment by jagjeet-singh** [comment]
Hi @lawchekun,
Thanks for raising the issue. It's likely that the `max_search_radius` was not big enough to get at least one nearby lane. It could be an object that is too far from all the lanes. Can you try increasing the `max_search_radius` and see if the problem still persists?
Alternatively, there is a similar function in the released baselines here: https://github.com/jagjeet-singh/argoverse-forecasting/blob/ba60688edf5770738d06d2a8472425dd3d60b049/utils/map_features_utils.py#L159
It will also fetch the candidate centerlines for you. 
Let me know if there are any questions.
Thanks!

**Comment by lawchekun** [comment]
Hi @jagjeet-singh,
Thanks for the reply!

I tried changing the `max_search_radius` to 200 but it still didn't work.
That is
`candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[1].city, viz=True, max_search_radius=200.0)`

Will try out the similar function in the released baselines to see if it makes a difference.

**Comment by jagjeet-singh** [comment]
Hi @lawchekun 
In your jupyter notebook, can you also check if `afl[4]` actually corresponds to `3828`. It's unlikely but there might be a case that this sequence is not at the expected index. So we might be passing the wrong city name to the function and hence don't get any nearby lanes.

**Comment by lawchekun** [comment]
Hi @jagjeet-singh
Thanks for the tip! Ah that explains, it shows `3700` for `afl[4]`, seems like `afl[2]` corresponds to 3828.csv`

**Comment by lawchekun** [comment]
Ok I got it working once I mapped the right csv file to the right index in `afl`. Somehow for my case, `afl[2]` corresponds to `3828.csv` and `afl[3]` to  `2645.csv`. Thanks for your help @jagjeet-singh !

**Comment by lawchekun** [comment]
Maybe instead of
```
seq_path = f"{root_dir}/2645.csv"
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[1].city, viz=True)

seq_path = f"{root_dir}/3828.csv"
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[4].city, viz=True)
```
We can do
```
index = 3
seq_path = afl.seq_list[index]
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[index].city, viz=True)

index = 2
seq_path = afl.seq_list[index]
agent_obs_traj = afl.get(seq_path).agent_traj[:obs_len]
candidate_centerlines = avm.get_candidate_centerlines_for_traj(agent_obs_traj, afl[index].city, viz=True)
```
So that the `csv` file and `afl` index are in sync?

**Comment by jagjeet-singh** [comment]
Thanks for the suggestion. I updated the tutorial.
