### ISSUE TITLE
Test dataset containts trajectories only for 2 sec.

### ISSUE THREAD

**Issue by sapan-ostic** [argoai/argoverse-api#127]
Hi,

I wanted to know if the test dataset contains only trajectories for 2 sec, how can perform the testing as mentioned in the paper.

**Comment by James-Hays** [comment]
To get scores on the test set, you can submit to our evaluation server here: https://evalai.cloudcv.org/web/challenges/challenge-page/454/overview

The evaluation server is always up, regardless of whether we are running competitions or not (and we currently are, for this CVPR workshop http://cvpr2020.wad.vision/
The evaluation server will report a dozen or so metrics on the test set, but if you want to evaluate with custom metrics you can instead evaluate with the validation set. 

The evaluation server is also rate limited to two submissions per day, so if you have an ablation study you want to do with dozens of algorithm variations, again you would want to use the validation set instead.
