### ISSUE TITLE
render_local_map_bev_mpl and render_local_map_bev_cv2 missing

### ISSUE THREAD

**Issue by jzuern** [argoai/argoverse-api#131]
Some map API functions mentioned on [the website](https://www.argoverse.org/data.html) seem to be missing in this repo. 
This includes `render_local_map_bev_mpl` and `render_local_map_bev_cv2`. Are there any plans to add them soon?

**Comment by johnwlambert** [comment]
Hi @jzuern , thanks for bringing this to our attention. Some functionality we haven't explicitly incorporated into the Map API yet, however we include it elsewhere in our repo.

For a global semantic rendering of the map, we have [render_global_city_map_bev](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_viz_helper.py#L100)

I believe what you are looking for is the following -- for a local semantic rendering of the map, we have [render_bev_labels_mpl](https://github.com/argoai/argoverse-api/blob/master/demo_usage/visualize_30hz_benchmark_data_on_map.py#L220)

In the [map demo notebook](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb
), we show the outputs of `render_bev_labels_mpl`:
<img width="589" alt="Screen Shot 2020-05-27 at 1 42 14 PM" src="https://user-images.githubusercontent.com/16724970/83054283-2f3ac600-a020-11ea-9404-d9422a7885e6.png">
<img width="609" alt="Screen Shot 2020-05-27 at 1 42 08 PM" src="https://user-images.githubusercontent.com/16724970/83054284-31048980-a020-11ea-943e-bf2e06fae01e.png">

Explicitly adding `render_local_map_bev_mpl` and `render_local_map_bev_cv2` to the API is something we hope to add in the near future -- feel free to open a pull request if you have a chance to add it.

**Comment by benjaminrwilson** [comment]
I believe this is resolved. Feel free to open another issue if you have additional questions!
