### ISSUE TITLE
id_gts referenced before assignment in eval_tracking.py

### ISSUE THREAD

**Issue by apak-00** [argoai/argoverse-api#137]
If provided an empty or non-existent folder to [eval_tracking.py](https://github.com/argoai/argoverse-api/blob/master/argoverse/evaluation/eval_tracking.py), `id_gts` on line [272](https://github.com/argoai/argoverse-api/blob/master/argoverse/evaluation/eval_tracking.py#L272) will throw a referenced before assignment exception.

**Comment by alliecc** [comment]
Hi @apak-00, thanks for the feedback. We are looking into adding warnings for this in the code. Please make sure that your paths are correct for now.

**Comment by benjaminrwilson** [comment]
@apak-00, feel free to submit a PR for this change! Closing the issue for now.
