### ISSUE TITLE
All I need is to submit the testing case, is that right?

### ISSUE THREAD

**Issue by mengde-cmd** [argoai/argoverse-api#138]
Hi 
My team have submitted the result of testing case successfully. But we found the evaluation result may be wrong. Our team has the lower FN and FP compare with  baseline method,  but our IDF1 score is only about half of the first place. 

We know that:

- the IDF1 score is only related to FN, FP and TP. 

- TP = (total ground truth - FN)

So,  do we lose some case?

**Comment by johnwlambert** [comment]
Hi @mengde-cmd, were you able to determine the issue on your end, or would you like to us look further into this?
