### ISSUE TITLE
Where is the render_local_map_bev_cv2 function and render_local_map_bev_mpl function?

### ISSUE THREAD

**Issue by sennnnn** [argoai/argoverse-api#139]

**Comment by sennnnn** [comment]
Does the render_global_city_map_bev have the same function? The API documentation is too simple to grasp the usage of argoverse dataset. So, do you have any plan to complete the API documentation?

**Comment by sennnnn** [comment]
Besides, what is the AV object?

**Comment by johnwlambert** [comment]
By AV, we mean autonomous vehicle. Are you referring to the forecasting dataset's "AV"? If so, this link might be helpful: https://github.com/argoai/argoverse-api/issues/58

We are happy to continue to improve the documentation. Could you let us know which parts of our API you find especially confusing, or where you find documentation missing?

**Comment by sennnnn** [comment]
Ok, I get it. The API about lane have not a detail explanation. although I have already know about the usage of the lane API.
