### ISSUE TITLE
The difference between evaluation data set and test data set

### ISSUE THREAD

**Issue by fanfanfanf** [argoai/argoverse-api#140]
We trained a model with train data set, and evaluate it with evaluation data set. The result we got on evaluation data set is : ade1(1.63), fde1(3.47), mr1(0.58), ade6(0.77), fde6(1.3), mr6(0.13), but the result we submitted on test data set is : ade1(2.34), fde1(5.23), mr1(0.73), ade6(1.28), fde6(2.36), mr6(0.29).  Why is there such a big gap between them? Are there many differences in data distribution?

**Comment by MohammadHossein-Bahari** [comment]
Hello,
I have the same problem. Could you find the cause? It seems that the test and validation are close, but don't know what happened.
