### ISSUE TITLE
How to generate BEV rasterized drivable region map in the ego vehicle coordinate?

### ISSUE THREAD

**Issue by monghimng** [argoai/argoverse-api#143]
Hi,

We am trying to use the rasterized drivable region map in tracking. However, in order to so, we would need it in the ego vehicle coordinate, as all the objects and points are in ego vehicle coordinate, and most convolution neural network operate in the ego vehicle coordinate space, following the car's motion.

My first idea is to simply find the ego vehicle pose in the city coordinate, and transform the rasterized map so that the ego vehicle is in the center. However, given that roads can have incline, this can cause regions to be off due to the difference in vertical rotation. For example, consider a road of an incline of 15 deg, 50 meters on the BEV (I assume captured orthographically) is actually 52 meters in the ego vehicle coordinate, off by 2 meters!

My second idea is to first convert the rasterized map into 3D points, then use the SE3 to convert to the ego vehicle coordinate. This way, vertical rotation is also considered. But this is somewhat hacky and prone to error. I am wondering if you guys would have an idea to compute this more easily.

Thanks.

**Comment by monghimng** [comment]
Turns out there is a `find_local_lane_polygons` that is very handy for this :)

**Comment by johnwlambert** [comment]
Hi @monghimng, are you interested in lane geometry or the drivable area segmentation? If I understood correctly, you are looking to account for pitch, so that instead of creating a bird's eye projection of drivable area segmentation, you create a segmentation of a planar surface (with a plane fixated underneath the egovehicle's 4 wheels)?
