### ISSUE TITLE
Forecasting Challenge Winners

### ISSUE THREAD

**Issue by os1a** [argoai/argoverse-api#152]
Hi,

Could you please share the detailed of the winners at the autonomous drivining workshop at CVPR 2020 for the forecasting challenge?

Do you know if anyone is planning to release their source code?

I was at CVPR 2020 but missed that Friday to attend the workshop, but quite sure it was recorded and would like to watch it.

Best,
Osama

**Comment by johnwlambert** [comment]
Hi @os1a, the recorded video from CVPR 2020 WAD of Argoverse competition results can be found here: https://www.youtube.com/watch?v=Vcbj_peZT4Q
