### ISSUE TITLE
Motion Forecasting: Trajectory annotation method

### ISSUE THREAD

**Issue by RaghavaModhugu** [argoai/argoverse-api#154]
Hello,

I have trained a deep learning model for Motion Forecasting on Argoverse. could you please let me know the method or process of how the coordinates of the agents are obtained in the 3D world for Argoverse annotation and transferred to BEV? This will help me in improving the performance of my trained model.

Regards,
Raghava Modhugu

**Comment by RaghavaModhugu** [comment]
Hello, Just to add more context to my question above. I have gone through the "Argoverse: 3D Tracking and Forecasting with Rich Maps". The paper has details on the various reference co-ordinate systems used for annotations etc. It will be insightful for me to understand who the position of the agent in the 3D environment or BEV is resolved.

Thanks in advance

**Comment by johnwlambert** [comment]
Hi @RaghavaModhugu, in our paper we state, "_To sample enough of these interesting scenarios, we track objects from 1006 driving hours across both Miami and Pittsburgh and find vehicles with interesting behavior in 320 of those hours"_ . Are you looking for details on the tracker, or the conversion from 3d to the bird's-eye-view BEV? In the forecasting dataset, we provide object tracks directly in the city (i.e. map) reference system. 3d tracks can be converted to the BEV just by discarding the z-coordinate.

**Comment by RaghavaModhugu** [comment]
Hello @johnwlambert,

Thanks for your response. I am looking for the details of the tracker like algorithm/architecture and tools used for that purpose. Could you please provide those details?

Regards, Raghava Modhugu

**Comment by johnwlambert** [comment]
Hi @RaghavaModhugu, we can't say more about the tracker we used to mine those trajectories, but there is indeed some noise and error in the resulting tracks.
