### ISSUE TITLE
How can I get the metrics of my model on the test dataset ?

### ISSUE THREAD

**Issue by leoncesc** [argoai/argoverse-api#155]
How can I get the metrics of my model on the test dataset, such as ade, fde, mr, ade6, fde6, mr6 ?

**Comment by James-Hays** [comment]
Hi,

You would need to submit your test set results to our evaluation server here: https://evalai.cloudcv.org/web/challenges/challenge-page/454/overview

**Comment by johnwlambert** [comment]
Hi @leoncesc, thanks for your interest in our work. On the validation set, you can use https://github.com/argoai/argoverse-api/blob/master/argoverse/evaluation/eval_forecasting.py, which is the same file we use to evaluate test set submissions. Closing this issue for now, but please feel free to re-open it if you have further questions.
