### ISSUE TITLE
Suggested edit in 4) Install argoverse module instructions

### ISSUE THREAD

**Issue by kbaptistap** [argoai/argoverse-api#156]
On the **"4) Install argoverse module"**, suggest that if you get an "ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied" error, try `sudo pip install -e /path_to_root_directory_of_the_repo/` instead of `pip install -e /path_to_root_directory_of_the_repo/`

**Comment by johnwlambert** [comment]
Hi @kbaptistap, thanks for your suggestion. We would actually recommend a "user" install instead of "root" install, in case of such an error. Did you give that a try?

**Comment by johnwlambert** [comment]
Hi @kbaptistap, since we haven't heard back, we'll go ahead and close this for now, but feel free to re-open if you're still having issues with the installation.
