### ISSUE TITLE
Questions about the observation history

### ISSUE THREAD

**Issue by LuanDi1996** [argoai/argoverse-api#157]
Hi, 

I am doing motion prediction right now and need the data about the current **velocity, acceleration, and yaw**. Currently, I am using the observation waypoints with filters to calculate these values, but there are some noises. Therefore,  I would like to know if there are ground truth about these values or some other ideas to calculate these values.

Thanks

**Comment by jagjeet-singh** [comment]
Hi,

Thank you for your interest in Argoverse.
We don't have the ground truth values for velocity, acceleration, and yaw in the current version of Argoverse. Your approach is reasonable where you run a filter before computing these values. Let me know if that's not working out.

Thanks!

**Comment by LuanDi1996** [comment]
Hi again,

I have tried several filtering methods for the observed history, but most of them failed in yaw estimation, which is easy to check . Therefore do you have some other recommended methods or some original data from tracking about the yaw estimation?

Thanks.

**Comment by James-Hays** [comment]
The map can help with yaw estimation. For example, find the closest lane segment and assume that the yaw is the same as the lane direction. This might not work well in intersections, where there are many overlapping lanes. But vehicles moving through intersections tend to have velocity so you can estimate their yaw by their heading. But for parked cars the map can do a pretty decent job, and they never move so a tracking based yaw estimate wouldn't work.

**Comment by LuanDi1996** [comment]
Hi again,

Thanks for your quick reply. In my project, I only care about the forecasting target, so there won't be any parked cars. I wonder if you have the raw data of the forecasting target, which might contain the yaw information since many tracking algorithms could output the information. Many thanks again for your assistance.

Regards.

**Comment by James-Hays** [comment]
Sorry, we don't have any more data to release at this time.
