### ISSUE TITLE
Distance to the driveable area

### ISSUE THREAD

**Issue by leoncesc** [argoai/argoverse-api#160]
During the prediction task, how can I calculate the distance from predicted points to the driveable area? If predicted points are in the driveable area, the distance is zero, otherwise the distance is positive.

**Comment by johnwlambert** [comment]
Hi @leoncesc, thanks for your interest in our work. You are likely looking for the [distance transform](http://www.theoryofcomputing.org/articles/v008a019/v008a019.pdf), implemented in [OpenCV](https://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga8a0b7fdfcb7a13dde018988ba3a43042). 

While we don't have an explicit function for that, we do already use the distance transform with the drivable area. You can see where we do it here:
https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_api.py#L190
and
https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/dilation_utils.py#L8

Pedro Felzenszwalb and Daniel Huttenlocher. [Distance transforms of sampled functions](http://www.theoryofcomputing.org/articles/v008a019/v008a019.pdf). Technical report, Cornell University, 2004.

**Comment by leoncesc** [comment]
@johnwlambert Thanks, this seems helpful for me.
