### ISSUE TITLE
Question about the motion forecasting dataset

### ISSUE THREAD

**Issue by CuttlefishXuan** [argoai/argoverse-api#161]
Hi,

I have downloaded the motion forcasting dataset from https://www.argoverse.org/data.html#forecasting-link. For the motion forecasting dataset, how can I get the corresponding image sequence (map information) such as the following picture?

![image](https://user-images.githubusercontent.com/30437016/93434189-651af780-f8fa-11ea-915e-5d64b5025f1d.png)

**Comment by jagjeet-singh** [comment]
Hi,
Refer "Visualize Sequences" section of the demo usage notebook. It will help you generic such images 
https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_forecasting_tutorial.ipynb

If you are interested in generating videos instead, you can consider using this viz util
https://github.com/argoai/argoverse-api/blob/master/argoverse/visualization/generate_sequence_videos.py

Hope this helps!

**Comment by CuttlefishXuan** [comment]
I got it, thanks!
