### ISSUE TITLE
Data collection in different challenging weather conditions

### ISSUE THREAD

**Issue by RaghavaModhugu** [argoai/argoverse-api#164]
Hello,

The Argoverse dataset paper _Argoverse: 3D Tracking and Forecasting with Rich Maps_ says "The captured data spans different seasons, weather conditions, and times of the day." This is an interesting scenario in many ways. I have a few questions in that regard.

I am assuming that the sensors are mounted on the rooftop of the vehicle, Without some form of protective gear, the quality of data could be compromised. How are these sensors protected from rain and snowfall?
Did you find any issues like distortion, interference, signal outage in the sensory information due to the weather conditions or due to the use of protective gear?
Awaiting ur reply,

Regards,
Raghava Modhugu

**Comment by James-Hays** [comment]
Hi Raghava,

You're right, it can be difficult to deal with all of these things. You can actually find a blog post about how we address some of these challenges here: https://medium.com/self-driven/self-driving-bugaloo-how-ford-is-keeping-autonomous-car-sensors-squeaky-clean-43b2c5382061

**Comment by johnwlambert** [comment]
Hi Raghava, closing this issue for now since we haven't heard back from you. Feel free to re-open if you have additional questions.
