### ISSUE TITLE
pip install -e /path_to_root_directory_of_the_repo/

### ISSUE THREAD

**Issue by QingwuLiu-polymtl** [argoai/argoverse-api#165]
Hi,

Here is Qingwu, who is at the beginning of learning how to use argoverse. I would like to ask one question about installing argoverse. I pasted "pip install -e /path_to_root_directory_of_the_repo/"  into my terminal. It said as follows:

"ERROR: /path_to_root_directory_of_the_repo/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+)."

I searched it on the website but I didn't find a solution. Can you give me any advice about it? Thanks very much!

**Comment by QingwuLiu-polymtl** [comment]
I have already solved it. Thanks!

**Comment by Jenshuo** [comment]
I have the same problem
How did you solve it?

**Comment by choishai94** [comment]
Hi, 

I have same problem. so, Would you explain to me how you solved it?

Thanks very much!

**Comment by johnwlambert** [comment]
Hi @choishai94, are you doing something like this?
```bash
git clone git@github.com:argoai/argoverse-api.git
cd argoverse-api
pip install -e .
```
