### ISSUE TITLE
Trajectory Forecasting Submission Format

### ISSUE THREAD

**Issue by zhaone** [argoai/argoverse-api#167]
Hi, I could not find the document of the format of submission h5 file except the usage example and the comment of function `argoverse.evaluation.competition_util.generate_forecasting_h5` when I am going to evaluate my results of trajectory forecasting on evalAI. In the comment of generate_forecasting_h5, the input data is required to be in shape (9, 30, 2). Does that mean I need generate 9 trajectories for each test sample? And does the evaluation system accept prediction with different `K` (my model generate different number of trajectories for different sample). I would appreciate it if you could give a detailed introduction document of submission file or tell me where to find it.

**Comment by janesjanes** [comment]
Hi Zhaone,
The comment regarding (9,30,2) shape is outdated, sorry about that. It is (n, 30, 2) where n the number of your prediction which can be anything (but anything more than maximum guess allowed wouldn't be considered in the evaluation)

For the submission, you can submit any number of guesses per sequence. In `generate_forecasting_h5`, the argument `data` is a dictionary of trajectory, with the key being the sequence ID and the value is an array of size (n,30,2). In each sequence, n doesn't have to always be the same.

**Comment by zhaone** [comment]
I see, thanks for help

**Comment by sukritiverma1996** [comment]
How/where do I append a probability to my predicted trajectory?

**Comment by YueYao813** [comment]
> 

Hi @sukritiverma1996 , maybe it's too late to answer you. You can check the function "generate_forecasting_h5" in this file https://github.com/argoai/argoverse-api/blob/master/argoverse/evaluation/competition_util.py. And the probability is the last argument for this function.
