### ISSUE TITLE
Trajectory duration in forecasting task 

### ISSUE THREAD

**Issue by iacopocarlini** [argoai/argoverse-api#169]
In the forecasting train and val data, it looks like many sequences are not of 5 seconds duration, in contradiction to what is stated in the argoverse dataset description ("324,557 scenarios, each 5 seconds long, for training and validation ... sampled at 10 Hz").
 
Looking at the timestamps, in many cases (more than 10 thousand) sequences can even last for 8,9,10,...12 seconds, sometimes less than 5 (4,5, 3...) so it is not possible to split trajectories in first 2 secs and last 3 secs to perform forecasting as shown in tutorials. 

Am I checking timestamps the wrong way?

**Comment by James-Hays** [comment]
Hi,

You're right that the "tick" duration isn't a constant 100ms and thus the actual time elapsed in each scenario is not constant. See #124 for more discussion of this.

**Comment by iacopocarlini** [comment]
Thank you so much for the quick reply.
