### ISSUE TITLE
Errors when install the argoverse api

### ISSUE THREAD

**Issue by LuanDi1996** [argoai/argoverse-api#173]
Hi,

I had an error like this 
 Cloning https://github.com/daavoo/pyntcloud to /tmp/pip-install-wz1pfqh4/pyntcloud
_ERROR: Command errored out with exit status 128: git clone -q https://github.com/argoai/argoverse-api.git /tmp/pip-req-build-2__8vakn Check the logs for full command output_ when I am using the pip install -e, do you know how to fix that? It seems like a problem related to internet protocol.

Regards

**Comment by janesjanes** [comment]
Hi,
I never encounter that error before,  apparently it could mean a lot of things. This might help : https://stackoverflow.com/questions/9617336/how-to-resolve-git-did-not-exit-cleanly-exit-code-128-error-on-tortoisegit

**Comment by johnwlambert** [comment]
Can you post the full set of commands you ran here? Thanks.

**Comment by LuanDi1996** [comment]
Hi,
Thanks for your reply, it seems to be a SSL certificate problem, and I fix this error by updating the CA cert. So it is a problem releted to github when downloading some necessary code from github, rather than the Argoverse. Sorry for the trouble I made.
