### ISSUE TITLE
What does "OBJECT_TYPE" mean in the forecasting dataset?

### ISSUE THREAD

**Issue by liwangcs** [argoai/argoverse-api#174]
Does the "AV" represent the ARGO data acquisition vehicle?
What kind of object does the "AGENT" mean?
Can you explain what these three categories mean?

Thanks for your answer and help.

**Comment by jagjeet-singh** [comment]
Hi @liwangcs , there's a thread on this topic: https://github.com/argoai/argoverse-api/issues/79
Please let us know if there are any further questions.

Thanks!
