### ISSUE TITLE
There should be 323,557 sequences in total not 324,557 sequences in Argoverse Forecasting Dataset.

### ISSUE THREAD

**Issue by Edmund-Shi** [argoai/argoverse-api#175]
The [dataset description](https://www.argoverse.org/tasks.html) says there are 205,942 train sequences, 39,472 validation sequences and 78,143 test sequences.
![image](https://user-images.githubusercontent.com/19988234/99800121-da12e380-2b6e-11eb-8e25-b9add83b10ec.png)

But when I sum up these numbers, I got **323,557** sequences in total which is different from the results on the website.
![image](https://user-images.githubusercontent.com/19988234/99800576-8d7bd800-2b6f-11eb-83d3-23045c30c814.png)

Maybe your calculation is wrong. Or maybe I missed 1,000 sequences somewhere? 😕

**Comment by James-Hays** [comment]
Good catch. I updated the website. Thanks!
