### ISSUE TITLE
How to align stereo images with lidar?

### ISSUE THREAD

**Issue by f-sky** [argoai/argoverse-api#183]
Front stereo cameras are 5Hz, lower than lidar (10Hz). However, I cannot find method in API to align them. Is there any example to align them? Thanks!

**Comment by johnwlambert** [comment]
Hi @f-sky, thanks for your interest in our work. 

If you mean to find the corresponding stereo image for a given LiDAR sweep, you could use:
```python
from argoverse.data_loading.synchronization_database import SynchronizationDB
sdb = SynchronizationDB(dataset_dir)
stereo_img_fpath = '/home/c6911883-1843-3727-8eaa-41dc8cda8993/stereo_front_left/stereo_front_left_315978406898656464.jpg'
cam_timestamp = Path(stereo_img_fpath).stem.split('_')[-1]
log_id = Path(stereo_img_fpath).parent.parent.stem
sdb.get_closest_lidar_timestamp(self, cam_timestamp, log_id)
```
If you mean to find the corresponding LiDAR sweep for a given stereo image, you could use:
```python
from pathlib import Path

from argoverse.data_loading.synchronization_database import SynchronizationDB

sdb = SynchronizationDB(dataset_dir)
lidar_fpath = '/home/c6911883-1843-3727-8eaa-41dc8cda8993/lidar/PC_315978406720284000.ply'
lidar_timestamp = Path(lidar_fpath).stem.split('_')[-1]
log_id = Path(lidar_fpath).parent.parent.stem
sdb.get_closest_cam_channel_timestamp(lidar_timestamp, camera_name = "stereo_front_left", log_id=log_id)
```
You could also use "stereo_front_right" instead above. I usually use the [SimpleArgoverseTrackingDataLoader](https://github.com/argoai/argoverse-api/blob/master/argoverse/data_loading/simple_track_dataloader.py#L17) to procure these paths.

If instead by alignment you mean computing a rigid body transformation such that the stereo point cloud and LiDAR point cloud to match exactly in 3d space, we could discuss an optimization procedure for that.

**Comment by f-sky** [comment]
Thank you!

**Comment by f-sky** [comment]
What I mean is find the corresponding LiDAR sweep for a given stereo image. Thanks for your answer!
