### ISSUE TITLE
How can I convert my own map data to this API supported format?

### ISSUE THREAD

**Issue by the-snail-001** [argoai/argoverse-api#190]

**Comment by johnwlambert** [comment]
Hi @the-snail-001, thanks for your interest in our API. Do you already have driveable area segmentation data, vector lane graph data, and ground height surface data for your scene of interest?

**Comment by the-snail-001** [comment]
> @ the-snail-001，您好，感谢您对我们的API的关注。对于您感兴趣的场景，您是否已经具有可驾驶区域分割数据，矢量车道图数据和地面高度表面数据？

Thank you for your reply.
I have only two things now:
1. The coordinates (x,y,z) that make up the lane centerline .
2. The coordinates  (x,y,z) that make up the lane boundary.
How do I make a map_files the files directory, for the corresponding file formats, such as JSON, NPY and XML, to realize API reading? Do you use OpenStreetMap?

**Comment by the-snail-001** [comment]
> Hi @the-snail-001, thanks for your interest in our API. Do you already have driveable area segmentation data, vector lane graph data, and ground height surface data for your scene of interest?

Sorry, my previous question may be a little rough. Could you tell me the meaning and organization of the data stored in the following files
1、MIA_ 10316_ driveable_ area_ mat_ 2019_ 05_ 28.npy
2、MIA_ 10316_ ground_ height_ mat_ 2019_ 05_ 28.npy
3、MIA_ 10316_ halluc_ bbox_ table.npy
4、MIA_ 10316_ npyimage_ to_ city_ se2_ 2019_ 05_ 28.npy
5、MIA_ 10316_ tableidx_ to_ laneid_ map.json
6、pruned_ argoverse_ MIA_ 10316_ vector_ map.xml
If you can tell me the meaning and format of the data in the above files, I can make my own data set. Thank you very much!

**Comment by johnwlambert** [comment]
Hi @the-snail-001 , you can find how we convert the nuScenes map to the Argoverse map format here: https://github.com/bhavya01/nuscenes_to_argoverse/pull/5

It should provide the main overview of what you need.

It sounds like you do not have a driveable area segmentation (we provide 1 square meter resolution of 0/1 values) or a ground height surface map (also at 1 square meter resolution). You can ignore these files then:
```
1、MIA_ 10316_ driveable_ area_ mat_ 2019_ 05_ 28.npy
2、MIA_ 10316_ ground_ height_ mat_ 2019_ 05_ 28.npy
```
Since you have vector map data, you can create the following files pretty easily though if you follow the nuScenes-to-Argoverse converter I linked above:
```
3、MIA_ 10316_ halluc_ bbox_ table.npy
4、MIA_ 10316_ npyimage_ to_ city_ se2_ 2019_ 05_ 28.npy
5、MIA_ 10316_ tableidx_ to_ laneid_ map.json
6、pruned_ argoverse_ MIA_ 10316_ vector_ map.xml
```

The gist is that given a query location, we need a a fast way to find nearby lanes. Instead of looping over 10k items you can precompute a bounding box for each lane, and then in a vectorized fashion check to see if the xmin, ymin,  xmax, ymax are closeby to a query.

**Comment by johnwlambert** [comment]
The SE(2) transformation just maps the origin of the data matrix on disk (consider it an image) and to the city origin.

**Comment by the-snail-001** [comment]
> The SE(2) transformation just maps the origin of the data matrix on disk (consider it an image) and to the city origin.

could you tell me your email? I have some problem about detial,Thanks!

**Comment by johnwlambert** [comment]
Sure, you can reach me at johnlambert [at] gatech [dot] edu.

**Comment by johnwlambert** [comment]
Closing this since I haven't heard back from you, feel free to re-open later if needed.

**Comment by the-snail-001** [comment]
Thank you.I have been read the code  of nuscenes_to_argoverse,but I still can not to do it,it seems that use the point cloud。
I open all data file and read them，I think I can build that format if I konw the detials，such as MIA_ 10316_ driveable_ area_ mat_ 2019_ 05_ 28.npy  ，use 1 to express driveable and 0 to express unriveable.But the coordinate in matrix must be int and my Lane boundary  coordinate is float  point(x，y), how to deal it ?

**Comment by johnwlambert** [comment]
Hi @the-snail-001, driveable area and lane boundaries are not semantically equivalent.

In our [Argoverse paper](https://arxiv.org/pdf/1911.02620.pdf), we define driveable area (DA) as _"A driveable area is an area where it is possible for a vehicle to drive (though not necessarily legal). Driveable areas can encompass a road’s shoulder in addition to the normal driveable area that is represented by a lane segment."_

Several lane segments might span a road at any particular point, and thus the driveable area might be comprised of many different lane segments.

One coarse approximation of DA for nuScenes might be to take the union of lane polygons in nuScenes. nuScenes lane boundaries are polylines (vector objects), whereas driveable area is a raster object.

Which file are you attempting to use from `nuscenes_to_argoverse`?
