### ISSUE TITLE
Question about Lane Segment!

### ISSUE THREAD

**Issue by pjw1** [argoai/argoverse-api#192]
Hi! 
Thank you for this amazing job!

I'm parsing my own vector map data into argoverse like map data.
I have two question about lane segment, ("way" tag in "pruned_argoverse_XXX_... .xml" map data). 

1. What are criteria to group successive "node" into different "way"?
I guessed if some tag values such as "has_traffic_control", "turn_direction", "is_intersection" are same, it will be grouped into same way.
But I found many exceptions..

2. What are criteria to decide "has_traffic_control"?
I think there are lots of types of traffic control, such as stop sign, yield sign,  traffic light, max speed sign, etc.
Do you have explicit list of traffic control types?

Thank you very much!

**Comment by johnwlambert** [comment]
Hi @pjw1, thanks for your interest in Argoverse. We released the Argoverse HD maps in a format similar to "OpenStreetMaps".  You could read more about it [here](https://wiki.openstreetmap.org/wiki/Elements) or [here](https://labs.mapbox.com/mapping/osm-data-model/#:~:text=Nodes%20are%20the%20equivalent%20of,that%20represent%20a%20larger%20whole). They are loaded [here](https://github.com/argoai/argoverse-api/blob/master/argoverse/data_loading/vector_map_loader.py) and a LaneSegment is defined [here](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/lane_segment.py) in the API.

(1) Each "way" corresponds to a single lane segment. How continuous lane objects are subdivided into discrete lane segments is a proprietary detail we likely won't reveal.

(2) In the Argoverse HD maps, "has traffic control" is a lane segment attribute that is set to true if a sign or traffic light controls the legal behavior in that lane.

**Comment by johnwlambert** [comment]
@pjw1  I'll close this issue for now since I haven't hard back, but feel free to re-open if you have further questions.
