### ISSUE TITLE
Agent bounding boxes for the Forecasting dataset 

### ISSUE THREAD

**Issue by lioutasb** [argoai/argoverse-api#203]
The forecasting dataset provides only information about the agent's center point but I was wondering if there is a way of getting the size and yaw angle of the bounding box for each agent. Is this information included in the 3D Tracking dataset so I can query based on the `track_id`?

**Comment by James-Hays** [comment]
Hi @lioutasb,

Unfortunately, no, that information is not available. The forecasting dataset and the 3D tracking dataset don't overlap so you can't find the size or yaw there, either. But you're not the first person to ask for these attributes and we're keeping them in mind for future releases.

**Comment by lioutasb** [comment]
Thanks a lot for letting me know.
