### ISSUE TITLE
an error when using map api

### ISSUE THREAD

**Issue by muzi2045** [argoai/argoverse-api#22]
tried with opencv-python==4.1 and opencv-python==3.3.1
both occur this error when using ArgoverseMap()
![image](https://user-images.githubusercontent.com/12984898/60656091-6e4caf80-9e81-11e9-994c-60b0c3dffea1.png)

**Comment by jagjeet-singh** [comment]
`opencv-python==4.1.0` should have 3 values returned by `findContours()`. 
https://docs.opencv.org/4.1.0/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0
Can you recheck the version you are using? `pip install -e <path_to_argoverse_repo>` should install the appropriate version by default as well.

**Comment by muzi2045** [comment]
check it, even I comment line 166, there is still error occured in this line.
![image](https://user-images.githubusercontent.com/12984898/60692236-91ba3d80-9f07-11e9-9b0b-8bda3fa2ff9c.png)

**Comment by muzi2045** [comment]
change line 166 to
`_ , contours, hierarchy = cv2.findContours(...) `
it worked.
