### ISSUE TITLE
How to draw bounding box rectangle on bird eye vew

### ISSUE THREAD

**Issue by chowkamlee81** [argoai/argoverse-api#23]
Do you have any smaple code to display 2d bounding box on lidar bird eye view data. Kindly help

**Comment by johnwlambert** [comment]
Hello @chowkamlee81, yes we do. If you open the Argoverse map tutorial with `jupyter notebook argoverse_map_tutorial.ipynb` you will see a section `Visualize map on the data` with the following bird's eye view 2d bounding box rendering:

<img width="687" alt="Screen Shot 2019-07-04 at 10 05 48 AM" src="https://user-images.githubusercontent.com/16724970/60681307-acc37980-9e43-11e9-86a7-4afb7109cc0f.png">


`DatasetOnMapVisualizer.render_bev_labels_mpl()` will call `plot_bbox_2D(ax, bbox_ego_frame, color)` which is defined in `argoverse.utils.mpl_plotting_utils.plot_bbox_2D`
