### ISSUE TITLE
Inquiry of challenging scenarios

### ISSUE THREAD

**Issue by XIAOYEJIAYOU** [argoai/argoverse-api#230]
May I ask where I could find the subset of challenging scenarios that you've identified and, I wonder if  you have labelled different traffic scenarios such as intersection, roundabout and so on. Thanks for your time and help!

**Comment by James-Hays** [comment]
Hi @XIAOYEJIAYOU,

For everyone's context, this is referencing "subsets of challenging scenarios, such as those with high density of dynamic objects, unanticipated turns, lane changes, and scenarios in which previous winning methods performed poorly." that we will consider when awarding competition prizes. The quoted text is from the competition announcement. We had hoped to add a leaderboard column for this, but that won't happen in time for the competition.

To be clearer on what we're doing: we have used various heuristics to mine for different types of interesting and challenging scenarios. We'll report how top teams did on these different subsets at the workshop on autonomous driving at CVPR 2021 on June 20th.  At this point, we're not identifying which scenarios fall into these different categories, or even saying how many categories there are.  We might in the future.

I
