### ISSUE TITLE
How to get each lane boundary？

### ISSUE THREAD

**Issue by mengxingshifen1218** [argoai/argoverse-api#241]

**Comment by James-Hays** [comment]
Argoverse 1.1 does not have explicit lane boundaries. The map has centerlines, instead. Lanes have somewhat standard widths, though, so you can estimate the lane boundaries from the centerlines.

From our paper: https://arxiv.org/abs/1911.02620
"We observe that in Miami, lane segments that could beused for route planning are on average3.84m±0.89 wide. In Pittsburgh, the average width is 3.97m±1.04in width. Other types of lane segments that would not be suitable for self-driving, e.g. bike lanes, can be as narrow as 0.97m in Miami and as narrow as 1.06m in Pittsburgh."

The API uses a value of 3.8 meters when hallucinating lane area from centerlines:
https://github.com/argoai/argoverse-api/blob/f74093d845e3076350e01f1f3954b77e699ad89a/argoverse/utils/centerline_utils.py#L42

The approximation of lanes from centerlines works pretty well most of the time. Give the map API functions a try.
