### ISSUE TITLE
Windows unsupported should be bold

### ISSUE THREAD

**Issue by hugadams** [argoai/argoverse-api#25]
Hi,

I was excited to try this out and overlooked the statement that it's only supported on linux mac, and then only realized this after setting up a project and trying to pip-install.  Any issue if we make this more salient on the readme?

```
Requires Linux/MacOS, git, and Python 3.6+
```
vs (in bold)
```
Requires Linux/MacOS, git, and Python 3.6+.  **Windows not supported.**
````

Also, why is Windows not supported?  Is this something we could work on for you?

**Comment by alliecc** [comment]
Hi Adam, the reason why Windows is not supported for now is because some of the paths in current code base is not compatible with window ( '/' vs. '\' stuff).
