### ISSUE TITLE
How to download the older version?

### ISSUE THREAD

**Issue by cuiziteng** [argoai/argoverse-api#256]
Hiii, for some reason i Have to use the old version, where to download it, because the new version api can not find  ''STEREO_IMG_WIDTH, STEREO_IMG_HEIGHT, RING_IMG_HEIGHT, RING_IMG_WIDTH'' in argoverse.utils.camera_stats, I also wanna know where to find them, thx~

**Comment by johnwlambert** [comment]
Hi, these constants are now accessible as follows:

```python
>>> from argoverse.sensor_dataset_config import ArgoverseConfig
>>> ArgoverseConfig.camera_sensors.stereo_front_left.img_width
2464
>>> ArgoverseConfig.camera_sensors.stereo_front_left.img_height
2056
>>> ArgoverseConfig.camera_sensors.ring_front_center.img_height
1200
>>> 
```

**Comment by cuiziteng** [comment]
Thx~
