### ISSUE TITLE
Forecasting: missing  AV's first TIMESTAMP

### ISSUE THREAD

**Issue by stratomaster31** [argoai/argoverse-api#26]
First of all, thank you for sharing this dataset, which will be really useful for the research community.

I noticed that, in the forecasting dataset, the first TIMESTAMP contains the Agent's and Others' locations, but none for the AV. I guess there should be good reason for that...

Thank's!

**Comment by jagjeet-singh** [comment]
Can you point me to the specific sequence where the AV location is missing for the first timestamp?

**Comment by jagjeet-singh** [comment]
I've updated the sample dataset to not have this issue. You might have to download it again. 
P.S.: The train/val/test datasets dd NOT have this issue to start with. So you need not download those again.
