### ISSUE TITLE
HD-Maps for Tracking

### ISSUE THREAD

**Issue by ziqipang** [argoai/argoverse-api#268]
Hi, Thank you for the nice dataset!

I am new to Argoverse and I am wondering if the tracking dataset has both 3D LiDAR data and HD-Maps?

Thank you!

**Comment by johnwlambert** [comment]
Hi @ziqipang, thanks for your interest in our work.

Yes -- Argoverse 1.1's 3D Tracking Dataset includes sensor data and hd maps. You can get more familiar with the Jupyter notebooks here:

Sensor data for tracking, and 3d annotations:
https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_tracking_tutorial.ipynb

HD maps:
and https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb

There are also more details in our paper: https://arxiv.org/abs/1911.02620

**Comment by ziqipang** [comment]
Thank you John!
