### ISSUE TITLE
Public Detection or Examples working with 3D Detection Codebase

### ISSUE THREAD

**Issue by ziqipang** [argoai/argoverse-api#270]
Hi,

Thank you for your great benchmark! However, I have several questions that may need your answer.

Specifically, I am trying to run some detection algorithms on the tracking dataset. However, I find it very difficult to combine argoverse with some public codebase, such as mmdetection3d. Therefore, I am wondering:

1. If there are some public detection results for argoverse, and how may I find it?
2. Do you have available resources of applying mmdetection3d to argoverse? It could be really helpful.

Thank you!

**Comment by johnwlambert** [comment]
Hi @ziqipang, thanks for your interest in our work.

If you are looking to understand the mapping between the Argoverse 1.1 3d Tracking Dataset's data format, and other popular dataset formats, you can see the one way converters here from

nuScenes -> Argoverse 1.1: https://github.com/bhavya01/nuscenes_to_argoverse
Waymo Open -> Argoverse 1.1: https://github.com/johnwlambert/waymo_to_argoverse

While I haven't used the `mmdetection3d` library before, we have written code to perform inference on Argoverse data with repos like CenterPoint. You can see the adapter for CenterPoint inference code here: https://github.com/johnwlambert/argoverse-centerpoint-simplified.

On [our 3d detection leaderboard](https://eval.ai/web/challenges/challenge-page/725/overview), which has some public detection results for Argoverse, the CenterPoint models are #1 and #2, respectively.

**Comment by ziqipang** [comment]
Sorry for noticing this now. But thank you all the same!

By the way, I have found that your challenge page on eval-ai has provided a public detection, which is also helpful.
