### ISSUE TITLE
Argoverse-tracking demo error: self._log_list: invalid syntax

### ISSUE THREAD

**Issue by goksanisil** [argoai/argoverse-api#28]
Hi, 

I've installed the API and all the dependencies per the documentation. When I'm trying to run the Argoverse-tracking demo, I'm getting the following error in the 1st cell:

argoverse-api/argoverse/data_loading/argoverse_tracking_loader.py", line 42
    self._log_list: Optional[List[str]] = None
                  ^
SyntaxError: invalid syntax

Am I missing something?

Thanks in advance

**Comment by alliecc** [comment]
Hi goksanisil, 
Thanks for your interests on Argoverse! Did you install the dependencies to the python version you use to run tracking demo?

**Comment by janesjanes** [comment]
Hey @goksanisil  The demo runs fine for me. It's difficult to debug without knowing more details about the environment you are using. Can you give us more details?

**Comment by srujanpanuganti** [comment]
Hello,
I am having a similar issue. I use python 3.5.2. I see there are errors during installation of the package. Can you please help solving this issue. 

Thank You.

**Comment by alliecc** [comment]
Hi @srujanpanuganti, sorry for the inconvenience, some of the string format we used is not supported by python 3.5. Please use python3.6+
