### ISSUE TITLE
camera height for Argoverse videos

### ISSUE THREAD

**Issue by zeina-abuaisheh** [argoai/argoverse-api#286]
Hello,

Where could I find the height of the camera in meters for Argoverse videos?

Thanks a lot

**Comment by johnwlambert** [comment]
This value will differ slightly for each log.

However, as a general rule of thumb, the ring cameras are generally around 1.68 meters off of the ground. You can derive this from the calibration files for each log `vehicle_calibration_info.json` (example file data is below), which provides the pose of the camera sensors in the egovehicle coordinate system (also known as ` "vehicle_SE3_camera_"`). The egovehicle coordinate system's origin is located at the center of the rear axle (around 33 cm above the ground). Z points up (see bottom-left inset):
<img width="1029" alt="Screen Shot 2021-11-27 at 7 33 16 PM" src="https://user-images.githubusercontent.com/16724970/143724471-7b21f8e1-3146-4dfa-9988-6de0510616af.png">

Part of `vehicle_calibration_info.json`:
```json
{
  "camera_data_": [
    {
      "key": "image_raw_ring_rear_left",
      "value": {
        "focal_length_x_px_": 1405.2875676247684,
        "focal_length_y_px_": 1405.2875676247684,
        "focal_center_x_px_": 991.0536701398403,
        "focal_center_y_px_": 614.6572646050513,
        "skew_": 0,
        "distortion_coefficients_": [
          -0.17089990828800997,
          0.12198460666714447,
          -0.028465752018243123
        ],
        "vehicle_SE3_camera_": {
          "rotation": {
            "coefficients": [
              0.6122928820212344,
              -0.6135230179644687,
              -0.3504444657749796,
              0.35478952839900724
            ]
          },
          "translation": [
            1.1331683594454462,
            0.22922319415971137,
            1.3586830041554878
          ]
        }
      }
    },
    {
      "key": "image_raw_ring_front_center",
      "value": {
        "focal_length_x_px_": 1402.7679150197941,
        "focal_length_y_px_": 1402.7679150197941,
        "focal_center_x_px_": 981.7422076685901,
        "focal_center_y_px_": 610.7617664117456,
        "skew_": 0,
        "distortion_coefficients_": [
          -0.1688970042736768,
          0.11837140963206995,
          -0.024816794505246636
        ],
        "vehicle_SE3_camera_": {
          "rotation": {
            "coefficients": [
              0.4967372363037331,
              -0.5000173904299812,
              0.5031821481132892,
              -0.5000424513548993
            ]
          },
          "translation": [
            1.624149079605374,
            -0.0030615876218737445,
            1.3612996597210592
          ]
        }
      }
    }
...
}
```

Could you provide some more details about what you're trying to do here? If you're looking for a homography for IPM, you can use the Argoverse map ground height values to get a better approximation.

**Comment by zeina-abuaisheh** [comment]
I just saw your answer, thanks for the detailed answer. It's always very helpful and I appreciate the time you take to answer questions.
I actually have implemented a path prediction method, and for it I need the height of the camera, extrinsic and intrinsic parameters.

**Comment by johnlambert-argo** [comment]
Hi @zeina-abuaisheh, I'm going to go ahead and close this issue since I believe I answered your question, but feel free to re-open if you have additional questions/concerns.

**Comment by zeina-abuaisheh** [comment]
yes you really did perfectly, thanks for all of the help you have provided me
