### ISSUE TITLE
Regarding End2End Learning for Argoverse V2

### ISSUE THREAD

**Issue by jiaxiaosong1002** [argoai/argoverse-api#287]
Hi guys, first, thanks for your great dataset! And I am excited for the coming release of Argoverse v2!

I am a PhD student recently working on end2end learning for autonomous driving.  I am wondering whether it is possible to align some parts of the Perception and Motion in Argoverse v2? In other words, the trajectories of agents and HD-Map could has the raw sensor data like camera images and Lidar.

If not, do you have plans for release some correspondence information? Right now, there are barely no good public datasets for end2end learning. (nuScenes has large alignments error between Lidar and its image/HD-map). I believe it would be very helpful for the community if you guys could release the file. Just humbly hope it is possible.

Thank you for your time!

**Comment by James-Hays** [comment]
Hi,

Thanks for interest in Argoverse. We don't plan to release sensor data for the forecasting scenarios, either for Argoverse 1 or Argoverse 2.  

If it's critical for you to have both tracks and sensor data, I think you best be would be to either use a sensor dataset that has both (but is, of course, dramatically smaller than a forecasting dataset).

In between would be large sensor datasets, like ONCE or Argoverse 2's lidar dataset, that have tens of thousands of scenes, but lack ground truth trajectories. You could create trajectories with a tracking algorithm and treat those datasets like smaller forecasting datasets.

**Comment by jiaxiaosong1002** [comment]
Got it. Thanks for your time! Can't wait to see the wonderful Argoverse v2 :).
