### ISSUE TITLE
About the motion forecasting dataset

### ISSUE THREAD

**Issue by AIwuya** [argoai/argoverse-api#29]
First of all, thank you for sharing this dataset.
I have a problem, whether we have the video of forecasting dataset. 
Maybe it will be released? Our group are very interested in it.
Thank you~

**Comment by James-Hays** [comment]
Sorry, there isn't any sensor data associated with the forecasting dataset. But it's good to hear what people are interested in. 

The current forecasting dataset is about 400 hours of data and we have 7 cameras at 30fps so it would be difficult to work with a dataset of video that large.

If you're OK using smaller amounts of data, our 3D tracking dataset could be used or forecasting. It has more than 10,000 tracked objects. Many of the objects are static, though.

Then there are other recent AV datasets: nuScenes, Apolloscape tracking, and H3D. Waymo and Lyft have also announced, but not yet released, datasets.
