### ISSUE TITLE
Any news about Argoverse 2.0? Jan 23

### ISSUE THREAD

**Issue by YuqiangJia** [argoai/argoverse-api#294]
btw, is the time intervals in motion prediton dataset identical?

**Comment by James-Hays** [comment]
Hi,

All I can say about Argoverse 2.0 is that it will be released soon.

The tick rate in the Argoverse 2 motion forecasting dataset will be the same as Argoverse 1 (100 ms ticks), but the history and prediction horizon will both be larger. 

From https://openreview.net/forum?id=vKQGe36av4k
"The first 5 s of each scenario is denoted as the observed window, while the subsequent 6 s is denoted as the forecasted horizon."

**Comment by johnwlambert** [comment]
Hi @YuqiangJia, Argoverse 2.0 has now been released. You can find more information at the following sources:

Argoverse 2.0 Development Kit: https://github.com/argoai/av2-api
NeurIPS '21 Paper: [PDF](https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/file/4734ba6f3de83d861c3176a6273cac6d-Paper-round2.pdf)
Download Page/Website: https://www.argoverse.org/av2.html

**Comment by johnlambert-argo** [comment]
Hi @YuqiangJia, feel free to re-open this issue if you have additional questions.
