### ISSUE TITLE
Visualizing 2 stereo images

### ISSUE THREAD

**Issue by swdev1202** [argoai/argoverse-api#31]
I see there is a `make_grid_ring_camera` function to generate images with bounding boxes in `argoverse/visualization/visualization_utils.py`.

Is there a similar function call for stereo images?

**Comment by janesjanes** [comment]
Hey, 

we don't have existing function specifically for stereo images, but it's really simple to make one. `argoverse.visualization.visualization_utils.show_image_with_boxes` is the function you need.

For example:
```
camera = "stereo_front_left"
img = argoverse_data.get_image_sync(idx, camera=camera)
objects = argoverse_data.get_label_object(idx)
calib = argoverse_data.get_calibration(camera)
img_vis = Image.fromarray(show_image_with_boxes(img, objects, calib))
plt.imshow(img_vis)
```
