### ISSUE TITLE
Evaluation of models based on mmflow

### ISSUE THREAD

**Issue by luis2r** [argoai/argoverse-api#313]
I am using a model based on mmflow for the stereo challenge but I was not able to use the evaluation script provided for this challenge. So I adapted my evaluation script based on yours but I was not able to calculate two parameters:
 flops = FlopCountAnalysis(model, inputs)
activations = ActivationCountAnalysis(model, inputs) 
due to mmflow input format. Are my results acceptable without reporting flops and activations? Can you create a script to evaluate models based on mmflow?

**Comment by jhonykaesemodel** [comment]
Hi Luis, thanks for reaching out. 
Yes, please submit your results without flops and activations for now. We'll consider it.
I'll take a look at mmflow in the future and see if we can adapt to it.

**Comment by luis2r** [comment]
Thank you @jhonykaesemodel
