### ISSUE TITLE
Unable to submit using EvalAI CLI for Stereo Challenge

### ISSUE THREAD

**Issue by jeromepatel** [argoai/argoverse-api#314]
Hi, 
First of all, thank you for hosting a great challenge, the stereo matching seems really fun to work upon. I generated the results using provided tutorial for the stereo challenge using my own model but I am unable to submit the results using the EvalAI CLI script. The error I am getting is:
```Error: {'detail': 'Given token not valid for any token type', 'code': 'token_not_valid', 'messages': [{'token_class': 'RefreshToken', 'token_type': 'refresh', 'message': 'Token is invalid or expired'}]}```
I also tried submitting through the upload file option but it seems that there exists 400 MB size limit as well. As there is only one submission limit per day and considering the challenge is ending in a few days, I am hoping to get my submission results as fast as possible so that I can quickly do final changes before the last submission.  Thank you for your help. 
Regards,
Jyot

**Comment by jhonykaesemodel** [comment]
Hi Jyot, thanks for reaching out.
Have you tried adding your EvalAI account token to evalai-cli? 
If you go to [https://eval.ai/challenge/1704/submit](https://eval.ai/challenge/1704/submit) and select **Use CLI** you should be able to see the instructions to set your token and submit the file.
Please let me know if that works.

**Comment by jeromepatel** [comment]
Hi, Thanks for quick response,
Yes, I followed all the steps from authenticating to using the correct command for file submission. I'm not sure if the error is from this particular challenge submission but I think the evalAI CLI is in general having some issue. (I tried doing one sample submission for another challenge as well, which also gave the same error). To check whether my local configuration has some issue, I tried submitting to the stereo challenge using colab but again I faced the same error.

**Comment by jhonykaesemodel** [comment]
Could you try refreshing your token? In the EvalAI web interface, click on your username close to the Logout button, then click on **Get your Auth Token**, then click on **Refresh Token**. Then, you can try to set the CLI with the new token. If that doesn't work, I'll contact EvalAI.

**Comment by jeromepatel** [comment]
Thanks for the help, it did solve the problem. Now, I am able to submit to the challenge.
There is one small request, can you please increase the limit to around 5 submissions if possible? Again thanks for your help!!
