### ISSUE TITLE
Labels for the forecasting dataset?

### ISSUE THREAD

**Issue by HaoquanLiu** [argoai/argoverse-api#32]
Finally there is a dataset for trajectory prediction! Thank you for all the hard work sifting through the driving data just to extract the interesting data for prediction. I was wondering whether there are labels for the observed vehicles in terms of what they did in the data segments, such as lane change, turn left, etc. These are very useful for intention and trajectory prediction tasks.

**Comment by James-Hays** [comment]
There aren't labels like this, but it's great to hear this feedback as we consider future versions of the forecasting dataset.
