### ISSUE TITLE
Download Link for HD-Map is Expired

### ISSUE THREAD

**Issue by yuxinl915** [argoai/argoverse-api#320]
To whom it may concern,

So sorry to disturb you again! I noticed that the link for HD-Map download is expired. When I clicked on it, it returned a 404 NOT FOUND error. Could you please help me with that? Thanks!

Best,
Yuxin

**Comment by benjaminrwilson** [comment]
Hi @yuxinl915,

Are you trying to download the Argoverse v1.1 HD maps for Miami and Pittsburgh? The link at https://www.argoverse.org/av1.html works for me. Would you mind trying again?

Ben

**Comment by yuxinl915** [comment]
Thanks! This link works, but the one you provided in README.md Installation part 2 is expired.

**Comment by benjaminrwilson** [comment]
Great, thanks for pointing this out. I've updated the link!
