### ISSUE TITLE
Evaluation of Motion Forecasting Submission Failed

### ISSUE THREAD

**Issue by SwagJ** [argoai/argoverse-api#325]
Hi, 

After I submitted the h5 file onto eval.ai, it always shows submitted instead of finished. Is that something wrong with the website or my submission file? If the latter case, how can I figure out what problem my submission file has? I am looking forward to your reply. Thank you very much.

**Comment by Xiaoyu006** [comment]
Hi, 
May I know how did you resolve this issue? I am facing the same issue now. 
Thank you very much!
