### ISSUE TITLE
whats the margin of error of localization?

### ISSUE THREAD

**Issue by l1xiao** [argoai/argoverse-api#33]
Thanks for the dataset!
I did some visualization on the dataset and found that sometimes the velocity of the agent can change very fast between the continuous frames. It seems like the margin of error of localization is [-0.5m, 0.5m] by mine rough estimation. Is there any description for margin of error of localization?

**Comment by James-Hays** [comment]
It sounds like you're referring to the forecasting dataset? Yes, there is definitely localization error in some of the object tracks. We don't have any characterization of the typical errors.

**Comment by l1xiao** [comment]
Yes, I'm referring to the forecasting dataset. Thanks for your reply.
