### ISSUE TITLE
[bug] official website unable to open

### ISSUE THREAD

**Issue by littleDrew** [argoai/argoverse-api#331]
#### Bug call for fix
API website Unable to open, in readme, it refers this website : https://www.argoverse.org/

-------
**Argoverse API**
Official GitHub repository for [Argoverse dataset](https://www.argoverse.org/)

**Comment by lab176344** [comment]
Same issue

**Comment by James-Hays** [comment]
Hi,

It is back up, for now, but with the shutdown of Argo there may be more interruptions. We are trying to find alternative hosting arrangements for the dataset.
