### ISSUE TITLE
About OBJECT_TYPE

### ISSUE THREAD

**Issue by DopeEdisonLee** [argoai/argoverse-api#333]
HI! Thanks for your great work! 
I got confused about 'AV' and 'AGENT', I read all the previous issues but I'm still not sure. 
What's the difference between these two and 'OTHERS', I know what they represent for, I simply don't understand their difference in the codes and their roles in your forecasting dataset. 
Thanks for you help!

**Comment by wangxuanyi1993** [comment]
Hello and thank you for your question. Specifically, it refers to the autonomous vehicle AV, the vehicle AGENT that shows interest, and other objects of interest.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argoverse/argoverse-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月10日(星期一) 中午12:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[argoverse/argoverse-api] About OBJECT_TYPE (Issue #333)





 
HI! Thanks for your great work!
 I got confused about 'AV' and 'AGENT', I read all the previous issues but I'm still not sure.
 What's the difference between these two and 'OTHERS', I know what they represent for, I simply don't understand their difference in the codes and their roles in your forecasting dataset.
 Thanks for you help!

**Comment by DopeEdisonLee** [comment]
Thanks for your reply! 
Yes I understand that part, I think my question is why is there an AV in the dataset specifically? If AGENT is the one shows interest and should be predicted eventually, what's the difference between AV and OTHERS? Any special function of AV in your dataset or coding?

**Comment by wangxuanyi1993** [comment]
I have a general understanding of your problem. Where AV is an autonomous vehicle and it's a self-driving car, and you can look at the data set and each of the self-driving cars has an ID. When the ID is different, the vehicle it is interested in observing will be under an AV, that is, the ID is different.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argoverse/argoverse-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [argoverse/argoverse-api] About OBJECT_TYPE (Issue #333)





 
Thanks for your reply!
 Yes I understand that part, I think my question is why is there an AV in the dataset specifically? If AGENT is the one shows interest and should be predicted eventually, what's the difference between AV and OTHERS? Any special function of AV in your dataset or coding?

**Comment by DopeEdisonLee** [comment]
I think I got it, thanks! 
Btw, would you mind sending me the API documentation, can't open that link on your Github website. I got some trouble understanding the way you guys use HD Maps. 
Thanks again!
