### ISSUE TITLE
Question on projecting image with depth to camera coordinate

### ISSUE THREAD

**Issue by MengshiLi** [argoai/argoverse-api#34]
While using this API, we found the following code confusing: 
The input for this function is (u, v, depth), with u and v in the unit of pixel number, while the output for this function is (x,y,z), with x and y in the unit of meter. Is it proper to passthrough the input to output directly?

```
def project_image_to_cam(self, uv_depth: np.array) -> np.ndarray:
        """ Project 2D image with depth to camera coordinate.

        Args:
            uv_depth: nx3 first two channels are uv, 3rd channel
               is depth in camera coord.

        Returns:
            nx3 points in camera coord.
        """

        return uv_depth
```
Here is the path for the affected file:
`Argoverse/utils/calibration.py`

Pls refer to the utils for KITTI dataset as a reference:  https://github.com/MengshiLi/pseudo_lidar/blob/psmnet_train/preprocessing/kitti_util.py

Also here is another piece of code that shares the same issue:

```
def project_image_to_ego(self, uv_depth: np.array) -> np.ndarray:
        """ Project 2D image with depth to egovehicle coordinate.

        Args:
            uv_depth: nx3 first two channels are uv, 3rd channel
               is depth in camera coord. So basically in image coordinate.

        Returns:
            nx3 points in ego coord.
        """

        return np.linalg.inv(self.extrinsic).dot(self.cart2hom(uv_depth).transpose()).transpose()[:, 0:3]
```

**Comment by janesjanes** [comment]
Hi Mars,

Sorry for the confusion. 

We only have 2 coordinates here, ego-vehicle and camera coordinates (with each camera having their own coordinate system, unlike Kitti that projected all cameras into the same coordinate). So for us, image and camera is actually the same coordinate system for each camera. 

So since we are directly using camera coordinate, xy will be in pixel and z will be depth in meters from the origin.

Those `project_image_to_ego` `project_ego_to_image` and `project_image_to_cam` functions are out of date (and you should be using `project_cam_to_ego` `project_ego_to_cam` instead) 

I'll put a PR to remove them tomorrow, thanks for catching this!!

**Comment by MengshiLi** [comment]
Thanks for the quick reply!

It is true that image and camera are actually the same coordinate system for each camera in argo, but it doesn't mean xy (in meter) is equivalent to uv (in pixel). There is this transformation represented by the intrinsic matrix between them. We have realized each argo camera has its own coordinate system, and that is why argo's intrinsic matrix is 3x3, not like KITTI's 3x4. The root issue here is not the matrix dimension size, but argo's API forgets to apply intrinsic transformation. 

And we do need to convert from image(uv_depth) to Lidar. This conversion could be done essentially in two steps, first from image to rectified camera coordinate system (this is where the intrinsic matrix should be applied, but the API actually missed), and then from rect_camera coordinate system to ego coordinate system( as already done correctly by ```project_cam_to_ego```).  Remove ```project_image_to_cam``` doesn't fix the issue. It needs to be updated to incorporate the intrinsic transformation.

Sorry for not being specific enough when I mentioned KITTI's code. I was referring to the following code. 
```
def project_image_to_rect(self, uv_depth):
        ''' Input: nx3 first two channels are uv, 3rd channel
                   is depth in rect camera coord.
            Output: nx3 points in rect camera coord.
        '''
        n = uv_depth.shape[0]
        x = ((uv_depth[:, 0] - self.c_u) * uv_depth[:, 2]) / self.f_u + self.b_x
        y = ((uv_depth[:, 1] - self.c_v) * uv_depth[:, 2]) / self.f_v + self.b_y
        pts_3d_rect = np.zeros((n, 3))
        pts_3d_rect[:, 0] = x
        pts_3d_rect[:, 1] = y
        pts_3d_rect[:, 2] = uv_depth[:, 2]
        return pts_3d_rect

def project_image_to_velo(self, uv_depth):
        pts_3d_rect = self.project_image_to_rect(uv_depth)
        return self.project_rect_to_velo(pts_3d_rect)
```

**Comment by janesjanes** [comment]
Oh, I see what you mean now, thanks for the explanation! 

Yeah, you are right we need to use the intrinsic to project back from pixel. Ignore what I said earlier, we do need those projection function to go from image to egovehicle. That should be an easy fix, thanks for pointing that out!

**Comment by janesjanes** [comment]
closing with this pending PR: https://github.com/argoai/argoverse-api/pull/35

but feel free to reopen it if you have any issue
