### ISSUE TITLE
Installation issues for argoverse 1 api

### ISSUE THREAD

**Issue by Carrotsniper** [argoai/argoverse-api#343]
Sorry for asking it again. When I follow the instructions to install the API, the following errors happened:

![01a8beb9575ee2f736074015c712ce8](https://github.com/argoverse/argoverse-api/assets/36280292/eeea0e42-646d-4430-a367-0b5268d47822)

**Comment by Carrotsniper** [comment]
I have solved the problem. Anyone need help can let me know.

**Comment by erimsatar** [comment]
How did you solve it?
