### ISSUE TITLE
Annotations Quality Problems

### ISSUE THREAD

**Issue by SeanChanCXG** [argoai/argoverse-api#40]
I find some bad annotations. If these bad annotations are corrected, it would be benefical to training improvment.
example 1 : truck lidar points are out of cuboid. log 00c561b9-2057-358d-82c6-5b06d76cebcf ,
frame index 298
example 2 : Vehicles with incorrect annotations in the background
example 3 : two cars boxes are completely overlaping

**Comment by SeanChanCXG** [comment]
example 1 : truck lidar points are out of cuboid. log 00c561b9-2057-358d-82c6-5b06d76cebcf ,
frame index 298
![Selection_942](https://user-images.githubusercontent.com/22977129/61934030-eeb28c00-afb9-11e9-8e93-efe1bab558fe.png)

**Comment by johnwlambert** [comment]
Hi @SeanChanCXG, thanks for your feedback. We will be happy to improve specific annotations.

Could you provide the same plot with the lanes and egovehicle marked to get a better sense for which objects you are rendering here?

**Comment by johnwlambert** [comment]
If it's helpful @SeanChanCXG, here are rendered videos for `00c561b9-2057-358d-82c6-5b06d76cebcf` to help us debug together:

https://drive.google.com/open?id=18OgdMaFRqP4b3s5q6f8vfwVLXXxeHR0p
https://drive.google.com/open?id=1BqRFZaO0LSOkMljeWBsJRQlhF3ckzZRB
https://drive.google.com/open?id=1exdBbmd5x3gq1K7k3WPQV7YGzbQFak85
https://drive.google.com/open?id=1NtwKMg1ST-DvB18t2VCkkL6vnY3vLxwb
https://drive.google.com/open?id=1jBYxtmG8VO4zF1gKwHqMAmShLtBe548Q
https://drive.google.com/open?id=1o8fmHkPM9p2e2Ab8Qjx2aPk7CEpKYXZm
https://drive.google.com/open?id=1tJkP2x-k3o-bsCJX2UXmCQknveCJiS06
https://drive.google.com/open?id=1h3e23v0zwGwn6qxy5VJps5BdpkkFMLRv
https://drive.google.com/open?id=1--cn-O8yiSFyhB_OD49rHapIeOnr2wW7

**Comment by SeanChanCXG** [comment]
@johnwlambert  
here are the 2 corresponding objects in ring_front_left image. Better to see the Incorrectness in lidar coordinate space. Corresponding lidar_timestamp is 315969658820199000.
![Selection_943](https://user-images.githubusercontent.com/22977129/61944221-c2096f00-afcf-11e9-9383-de0dfd5bb673.png)

**Comment by SeanChanCXG** [comment]
on the same log, there are 2 boxes are completely overlapping. But they are not in the last few frames.
 lidar_timestamp is 315969631519847000
![Selection_944](https://user-images.githubusercontent.com/22977129/61944879-4b6d7100-afd1-11e9-8d5f-cbb4b8120e22.png)

![Selection_945](https://user-images.githubusercontent.com/22977129/61945079-b3bc5280-afd1-11e9-9412-55e893a8369a.png)

**Comment by johnwlambert** [comment]
@SeanChanCXG Thanks, we'll get these taken care of.

**Comment by johnwlambert** [comment]
@SeanChanCXG I think these show example (1) and example (3) from your list at the top. Could you explain example (2) *Vehicles with incorrect annotations in the background*?

**Comment by SeanChanCXG** [comment]
@johnwlambert sorry for the delayed reply.
here is example(2), thers is car box on the background (wall). you can check on argoverse-tracking/train1/1d676737-4110-3f7e-bec0-0c90f74c248f/lidar/PC_315984812120450000.ply
![Selection_963](https://user-images.githubusercontent.com/22977129/62100560-cf22a880-b2c4-11e9-998c-8ae2704758c5.png)

**Comment by johnwlambert** [comment]
Thanks @SeanChanCXG, the last issue you mentioned is one we already noticed and are actively fixing. It will be corrected in Argoverse v1.1.

**Comment by johnwlambert** [comment]
@SeanChanCXG Please see Argoverse v1.1 at https://www.argoverse.org/data.html for improved labels.

**Comment by johnwlambert** [comment]
@SeanChanCXG Our 3d tracking leaderboard is online -- if you're interested, feel free to submit an entry at https://evalai.cloudcv.org/web/challenges/challenge-page/453/leaderboard/1278
