### ISSUE TITLE
How to remove annotations on non-driveable area in "per_sweep_annotations_amodal" json files?

### ISSUE THREAD

**Issue by chowkamlee81** [argoai/argoverse-api#43]
Hi,
We used "leave_only_roi_region" which Return points that are on driveable area, and non-ground points.

But when we are using annotations data in "per_sweep_annotations_amodal" json files, how to remove annotations on non-driveable area.  Is there is any API to preprocessing way to remove redundant annotation data after removing non-driveable area from pointcloud.

Kindly help

**Comment by johnwlambert** [comment]
Hi @chowkamlee81, I believe you can use the following functions to accomplish your goal:

`def remove_non_driveable_area_points(self, point_cloud: np.ndarray, city_name: str) -> np.ndarray:`

`def remove_non_roi_points(self, point_cloud: np.ndarray, city_name: str) -> np.ndarray:`

`    def remove_ground_surface(`
`        self, point_cloud: np.ndarray, city_name: str, return_logicals: bool = False`
`    ) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:`

Suppose you start with a point cloud, and you keep only the points on the drivable area using `remove_non_driveable_area_points()`. This function doesn't take into account the ground surface at all, by the way. Suppose you have 3d cuboid annotations. You can pass the cuboid centroids as a 2d or 3d point cloud into `remove_non_driveable_area_points()` to discover which cuboids live within the drivable area.
