### ISSUE TITLE
Forecasting API extremely slow...

### ISSUE THREAD

**Issue by Wilco17** [argoai/argoverse-api#46]
The forecasting API is extremely slow when working with the train data set... I don't know if this issue is only happening to me... When working on the sample data set, everything works well

**Comment by jagjeet-singh** [comment]
Thank you for your interest in Argoverse.
The forecasting API was intended to introduce how to use forecasting sample dataset and map api. Training dataset has ~250k sequences and sample dataset has just 5. So it is expected to be much slower. 
You might want to use a smaller subset of training dataset, or just create a new script, borrowing code from forecasting dataloader, which does only what you need.
