### ISSUE TITLE
Details on forecasting baselines...

### ISSUE THREAD

**Issue by nnsriram97** [argoai/argoverse-api#47]
Hi, 

I would like to get a few more details on the forecasting baselines. 

1. Is there a function in the API which converts back the trajectory from lane coordinate system back to city coordinates? (nt to xy)
2. What are the map features _m_? Are those lane attributes like _"is_intersection"_, _"turn_direction"_, etc.? 
3. For NN+map only the trajectory coordinates that are converted to lane coordinates for a different hypothesis of lane centerlines are given as input to NN model? While for LSTM+map baseline the lane coordinates + some attributes are given as input? 
4. Are those map attributes given as input same over time for a particular trajectory?

**Comment by jagjeet-singh** [comment]
Hi,
Great questions!
1. There is no function in the API right now. But we will be releasing the baseline code soon which will have that along with several other utility functions.
2. The baselines played around with features like the ones you mentioned, but it didn't use any of them eventually. They mainly used `n,t` coordinates as the information gathered from map.
3. Both `NN+map` and `LSTM+map` used only `n,t ` lane coordinates
4. The map features also should change over time.

**Comment by gupta-abhay** [comment]
Question regarding map features -- if the map features change over time - do you mean that when we are using models like NN + map -- we are also predicting the map features over time ?? 

For example, at an intersection - the lane information can change (when the car goes left / right) - but the fact that the map is that of an intersection does not change. So how do you handle these scenarios in the prediction?

**Comment by johnwlambert** [comment]
@nnsriram97 You can find the forecasting baselines here: https://github.com/jagjeet-singh/argoverse-forecasting

**Comment by johnwlambert** [comment]
@nnsriram97 Our motion forecasting leaderboard is here, if you would be interested in submitting an entry: https://evalai.cloudcv.org/web/challenges/challenge-page/454/leaderboard/1279
