### ISSUE TITLE
Is the vehicle action information included in the Motion Forecasting datasets ?

### ISSUE THREAD

**Issue by leoncesc** [argoai/argoverse-api#48]
This dataset is great, and it is very helpful for some related research. I have two qustions for you as described below.
1. Is the vehicle action information included in the Motion Forecasting datasets ? vehicle action maybe classified into sevral classes: lane keeping, left lane change, right lane change, turn right, turn left, U turn ?
2. Can we acess to velocity and orientation of vehicle in the Motion Forecasting datasets ?

**Comment by jagjeet-singh** [comment]
Thank you for your interest in Argoverse! 
1. We have not provided such action labels in the first version of Argoverse. We are discussing more about this within the team. 
2. The velocity and orientations were not included. An estimate of velocity can be obtained from the trajectory as the the frequency is fixed (10Hz).

**Comment by leoncesc** [comment]
> Thank you for your interest in Argoverse!
> 
> 1. We have not provided such action labels in the first version of Argoverse. We are discussing more about this within the team.
> 2. The velocity and orientations were not included. An estimate of velocity can be obtained from the trajectory as the the frequency is fixed (10Hz).

Thanks for your reply.
If I want to label the vehicle action in the Motion Forecasting datasets, what's your suggestion? In other words, how can I annotate the vehicle action in this dataset correctly and efficiently?

**Comment by jagjeet-singh** [comment]
Sure, it depends on what actions you want to annotate. There'll be some heuristics for annotating each action. Some examples:
1. ` left lane change, right lane change`: You can use the map. If the trajectory switches from a lane to it's left/right neighbor, the action can be annotated as lane change
2. `turn right, turn left`: Either you can use the map to determine if the vehicle is in left/right turn lane, or you can directly infer it from the trajectory curvature.
3. `U turn`: Can determined using trajectory curvature.

**Comment by leoncesc** [comment]
> Sure, it depends on what actions you want to annotate. There'll be some heuristics for annotating each action. Some examples:
> 
> 1. ` left lane change, right lane change`: You can use the map. If the trajectory switches from a lane to it's left/right neighbor, the action can be annotated as lane change
> 2. `turn right, turn left`: Either you can use the map to determine if the vehicle is in left/right turn lane, or you can directly infer it from the trajectory curvature.
> 3. `U turn`: Can determined using trajectory curvature.

Thank you very much!
