### ISSUE TITLE
Synchronization issue while instantiating ArgoverseTrackingLoader

### ISSUE THREAD

**Issue by divatekodand** [argoai/argoverse-api#49]
Hello,
 I receive the following error message while instantiating ArgoverseTrackingLoader using the entire dataset.

##ArgoverseTrackingLoader
import argoverse
from argoverse.data_loading.argoverse_tracking_loader import ArgoverseTrackingLoader
​
##set root_dir to the correct path to your dataset folder
root_dir =  '../../argoverse-tracking/test/'
​
argoverse_loader = ArgoverseTrackingLoader(root_dir)
​
print('Total number of logs:',len(argoverse_loader))
argoverse_loader.print_all()

ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 120.935344 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 120.9344 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 100.002096 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 117.39392 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 117.396904 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 118.257336 > 100.0 ms
ERROR:argoverse.data_loading.synchronization_database:No corresponding image: 118.252632 > 100.0 ms

**Comment by janesjanes** [comment]
Hi @divatekodand 
Thanks for letting us know about the error. That is because it couldn't find some stereo images that are close enough in time to the lidar frame, we will fix that in the next release version of Argoverse dataset. If you don't need those missing stereo images, you can just ignore the errors and everything else will still run fine.

**Comment by janesjanes** [comment]
related: https://github.com/argoai/argoverse-api/pull/53 

closing this for now

**Comment by cdahms123** [comment]
Still getting this error in December 2021 with Argoverse 1.1 please resolve or re-open issue

**Comment by janesjanes** [comment]
Hey cdahms123,
Can you tell us more about which log did you get the errors? 

Thanks!
