### ISSUE TITLE
Get the agent coordinates wrt to map_file xml coordinates

### ISSUE THREAD

**Issue by varunvelugoti** [argoai/argoverse-api#51]
Hi
I got the agent coordinates from forecasting csv data, trying to map these coordinates with coordinates that are present in xml.
Does anyone know what coordinates are represented in the map file xml ?

**Comment by sujithvemi** [comment]
I think they are the same. Check section 1.1 in [supplemenatal material.](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf)
