### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by fanfanfanf** [argoai/argoverse-api#54]
Hello! I try to install the package and failed with the following messages:

`error in argoverse setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in pyntcloud @ git+https://github.com/daavoo/pyntcloud#egg=pyntcloud-0.1.0 at  @ git+https://github.com/daavoo/pyntcloud#egg=pyntcloud-0.1.0`

python: 3.6.1
pip: 19.2.3
setuptools: 41.2.0

**Comment by johnwlambert** [comment]
Hi @fanfanfanf, were you able to resolve the issue?
