### ISSUE TITLE
Coordinate transform problem

### ISSUE THREAD

**Issue by leoncesc** [argoai/argoverse-api#55]
I have some question about coordinate transform.

First, what is the explicit definition of  2-d curvilinear coordinate system with axes tangential and perpendicular to the lane centerline(as explained in the argoverse paper in CVPR, Argoverse: 3D Tracking and Forecasting with Rich Maps: we define a 2-d curvilinear coordinate system with axes tangential and perpendicular to the lane centerline.)， it is easy to understand when the lane is straight, but it is confused to me when the center line of the reference lane is a curve.

Second, how can I transform the city coodinate to some lane coordinate.

Thirdly, is there some demo or document about often used coordinate transform？

**Comment by jagjeet-singh** [comment]
Hi!
Hope this image helps in understanding the transformations.
![image](https://user-images.githubusercontent.com/11771909/64363160-e3517800-cfdd-11e9-9eca-09f1469e4f2c.png)
Transforming (x,y) to (a,o) is what we call transforming city coordinates to lane coordinates. Once you have the centerline, you can project the (x,y) coordinates to the centerline (eg. using `Shapely`) and get the distance along the centerline using that projected point. Offset from the centerline is just the distance between the (x,y) coordinate and the projected point. Hope this helps.

**Comment by leoncesc** [comment]
> Hi!
> Hope this image helps in understanding the transformations.
> 
> ![image](https://user-images.githubusercontent.com/11771909/64363160-e3517800-cfdd-11e9-9eca-09f1469e4f2c.png)
> Transforming (x,y) to (a,o) is what we call transforming city coordinates to lane coordinates. Once you have the centerline, you can project the (x,y) coordinates to the centerline (eg. using `Shapely`) and get the distance along the centerline using that projected point. Offset from the centerline is just the distance between the (x,y) coordinate and the projected point. Hope this helps.

Thank you so much ! 
Further question is that the distance along the centerline is with respect to the start position of the centerline ?

**Comment by jagjeet-singh** [comment]
yes
