### ISSUE TITLE
Does the map data have curvature information of the road?

### ISSUE THREAD

**Issue by sujithvemi** [argoai/argoverse-api#56]
I have gone through some of the code for loading the map data. It does a good job of explaining what is being done. But I want to understand whether it contains curvature information of the road, can you please provide info on this?

**Comment by johnwlambert** [comment]
Hi @sujithvemi, please take a look at Figure 1 of [the Supplemental Material](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf). Our lane centerlines trace every road lane, and thus capture their curvature. Is there specific curvature information you are looking for?

**Comment by sujithvemi** [comment]
Hi @johnwlambert, thank you for the prompt response. I was actually looking for the value of curvature at each point. I was working with Apollo and I initially thought the curvature info is given in HDMap itself, but I was wrong. I will try to write code for calculating the curvature of a point and push it.

**Comment by mpourkeshavarz** [comment]
@sujithvemi 
did you figure out a way to find the curvature of a point? did you try to find lane segment curvature?

Best,
Mozhgan
