### ISSUE TITLE
Supplemental Material of paper?

### ISSUE THREAD

**Issue by yzl96** [argoai/argoverse-api#57]
Hi, I don't see the Supplemental Material in the end of the paper, can you tell me where I can get these supplemental materal?

**Comment by johnwlambert** [comment]
Hi @yzl96, you can find the link to the [Supplementary Material here](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf) (it's linked at the bottom of [this CVPR 19 html page](http://openaccess.thecvf.com/content_CVPR_2019/html/Chang_Argoverse_3D_Tracking_and_Forecasting_With_Rich_Maps_CVPR_2019_paper.html)).

**Comment by yzl96** [comment]
thank you
