### ISSUE TITLE
Map Features over Prediction Interval

### ISSUE THREAD

**Issue by gupta-abhay** [argoai/argoverse-api#60]
```4. The map features also should change over time.```

_Originally posted by @jagjeet-singh in https://github.com/argoai/argoverse-api/issues/47#issuecomment-519692798_ 

Question regarding map features -- if the map features change over time - do you mean that when we are using models like NN + map -- we are also predicting the map features over time ?? 

For example, at an intersection - the lane information can change (when the car goes left / right) - but the fact that the map is that of an intersection does not change. So how do you handle these scenarios in the prediction?

**Comment by jagjeet-singh** [comment]
The map features do change over time, but we account for that in the observed 2 secs of the trajectory, not in the future 3 secs. As such, NN+map will do a look up using map features for the observed 2 secs, and will only predict the locations (not other map features) for future 3 secs.

For your example, I'm not sure I understand the question completely. Since the vehicle's location is changing, we can assume all the map features can change over time. Why should "the fact that the map is that of an intersection does not change" impact anything?

**Comment by leoncesc** [comment]
In` NN+map(oracle) or LSTM ED+map(oracle)`, inputs are only `n, t `lane coordinates, and only `n, t `lane coordinates for future 3 secs are predicted.

My first question is that the AGENT may perform a lane change action(maybe in the first 2 secs, may be in the future 3 secs), so which lane coordinate system are the predicted `n, t `lane coordinates with respect to ?

My second question is how does the` LSTM ED+map` model get top `K` hypothesized centerlines, in other words, how to get multiple hypothesized centerlines?

My last question is how does the forecasting model predict the future locations when the observed trajectory is less 2 secs ?

> The map features do change over time, but we account for that in the observed 2 secs of the trajectory, not in the future 3 secs. As such, NN+map will do a look up using map features for the observed 2 secs, and will only predict the locations (not other map features) for future 3 secs.
> 
> For your example, I'm not sure I understand the question completely. Since the vehicle's location is changing, we can assume all the map features can change over time. Why should "the fact that the map is that of an intersection does not change" impact anything?

**Comment by jagjeet-singh** [comment]
> My first question is that the AGENT may perform a lane change action(maybe in the first 2 secs, may be in the future 3 secs), so which lane coordinate system are the predicted n, t lane coordinates with respect to ?
Good point. The current heuristics for oracle centerline will not account for the lane change (to a neighbor). It will provide only one of the two centerlines as the oracle. But it should be possible to update the heuristics to switch the centerline if there's lane change.
> My second question is how does the LSTM ED+map model get top K hypothesized centerlines, in other words, how to get multiple hypothesized centerlines?
You can use `get_candidate_centerlines_for_traj()` from map_api to get most likely centerlines that the trajectory is following. Then you can do the inference along each of those candidate centerlines.
>My last question is how does the forecasting model predict the future locations when the observed trajectory is less 2 secs ?
Currently, the task is restricted to just the `AGENT` class, which is always observed for 2 secs. If you are interested in varying observed lengths for other actors in the scene, LSTM should work just as fine (with some padding if you want to do batching). For NN you might have to do some sampling from the trajectory to have a consistent feature size.

**Comment by leoncesc** [comment]
Thanks for your reply. Regarding my first question, the predicted locations in future are with respect to the centerline which the last observed position of AGENT belong to ?

**Comment by jagjeet-singh** [comment]
The centerline would be more accurate if it is obtained using the entire observed trajectory, and not just the last coordinate.

**Comment by leoncesc** [comment]
Regarding the second question, the forecasting task is a multimodal problem. As you pointed out that we can get multiple hypothesized centerlines, but we usually need to know which centerlines is the most likely one. So how can we get the confidence of the multiple centerlines ?
Thanks for your patience ! @jagjeet-singh

**Comment by jagjeet-singh** [comment]
Confidence over candidate centerlines will depend on how you are computing those.
Consider a very simple approach. If you have `k` possible centerlines and `n` coordinates in the trajectory, you can check what proportion of those `n` coordinates lie within the lane polygons for each of those `k` centerlines (basically, `point in polygon score`). Higher the proportion, higher the score.
If you are using a learned classifier instead of heuristics, the probability over each of those `k` centerlines can serve as the score.

**Comment by johnwlambert** [comment]
@leoncesc @gupta-abhay You can find the forecasting baselines here: https://github.com/jagjeet-singh/argoverse-forecasting

**Comment by gupta-abhay** [comment]
@johnwlambert thank you for the update. We are working towards a submission for the NeurIPS challenge. This will definitely help us with that.

**Comment by James-Hays** [comment]
That's great to hear that you're participating in the challenge. I hope you find a way to do much better than the baselines!
