### ISSUE TITLE
wrong labeled object

### ISSUE THREAD

**Issue by yzl96** [argoai/argoverse-api#61]
Hi, I'm using argo dataset, I find some wrong label for car when checking the dataset, for example, in sequence 75756160_7575_7575_7575_675757273088, for object whose tracking id is 64, start from PC_315980055919835000, is wrong labeled for about 10 frames, 
![image](https://user-images.githubusercontent.com/31734981/64665826-9a3e6f80-d486-11e9-8000-0422b41012ac.png)
the red one.

what's more, in the sequence,PC_315980061220240000,  one object is not labeled:

![image](https://user-images.githubusercontent.com/31734981/64665790-63685980-d486-11e9-9d77-5573c85423c5.png)

I think maybe you should carefully check the quality of label.

**Comment by janesjanes** [comment]
Hi @yzl96 

Thanks for your feedback, we will definitely fix that in the next version of our release.

**Comment by johnwlambert** [comment]
@yzl96 Please see Argoverse v1.1 at https://www.argoverse.org/data.html for improved labels.
