### ISSUE TITLE
IN LIDAR pointclouds why no intensity information not captured?

### ISSUE THREAD

**Issue by chowkamlee81** [argoai/argoverse-api#62]
Hi,

I observed point cloud of LIDAR data doesn't have any intensity information only X,Y,Z information. Can you kindly specify what was the reason? Kindly suggest

**Comment by janesjanes** [comment]
Hi @chowkamlee81 
The ply file for our lidar does contain intensity. We simply haven't load that in the api currently, you can just create your own function to load that up.

**Comment by xmyqsh** [comment]
@johnwlambert @jagjeet-singh 
Hello, I'm wondering about the use of the `intensity` of the lower lidar in the upper lidar coordinate system. In other words, when we store the point cloud of the upper and lower lidar together in the same `.ply` file in the world coordinate system, the `intensity` field has lost its meaning. We could only use the `intensity` field when we separate them apart as [diff.patch#L71](https://github.com/irenecortes/argoverse_lidar/blob/master/diff.patch#L71) does.
Am I right?
