### ISSUE TITLE
Filtering out instances with stop signs

### ISSUE THREAD

**Issue by abhimohta** [argoai/argoverse-api#63]
I'm looking at a particular problem where I need to filter out instances for forecasting where actors/AV paused at a stop sign and then continued motion. I was trying to go through the map API to get annotated labels of lanes, etc. but couldn't find anything. Any guidance on what's the best way to extract such data?

**Comment by abhimohta** [comment]
If I have a list of lane segment IDs I want to concentrate on, any guidance on how I can filter all snippets across all the logs that pass through that lane segment?

**Comment by jagjeet-singh** [comment]
Brute force would be:
1. Get the centroid `x,y` at each frame for the track.
2. Use `get_lane_segments_containing_xy()` to get the list of lane segments.
3. Check if this list contains any lane from your list.

**Comment by vadeshah** [comment]
Hi all! Sorry for digging up an old issue - I've been working with the argoverse dataset for a few months now, and I've recently also started to attempt to isolate intersections with stop signs.

@abhimohta I was wondering if you had any success on extracting the stop sign information, and if so, what method did you use?
@James-Hays is there a convenient way to load in the map data as an OpenStreetMap file? I see that the data is stored as a modified OSM form, but I'm a little new to OSM files in general, so I'm not quite sure how to work with the raw data files themselves (like pruned_argoverse_MIA_10316_vector_map.xml) and determine whether or not an intersection contains a stop sign from this data.

Thank you for your help in advance!
