### ISSUE TITLE
Filtering trajectories values (x,y locations, signal processing)

### ISSUE THREAD

**Issue by stratomaster31** [argoai/argoverse-api#64]
Hi again,

I think it makes sense to pre-process the trajectories: for instance, agent's heading computation is very sensitive to noisy data.

What I'm doing, from a batch processing approach (off-line processing) is a parametric curve fitting: I fit separately x and y locations with two polynomials with degree=3, using a parameter t from 0 to 1. After that, using this polynomials evaluated in t I get quite well filtered x and y locations, and for even complex trajectories this low order polys work well. My concerns are:

1. Any suggestion for a better filtering technique? I tried golay filtering, but it does not smooth too much...
2. For a real time processing approach: Klaman (EKF,UKF) or particle filtering would work well?

**Comment by James-Hays** [comment]
Hi,
That's interesting that you're testing these different smoothing methods. The tracks can certainly be noisy so smoothing makes sense before you do heading estimation. I don't have any specific advice about smoothing methods. One concern is that many of the tracked objects are static (e.g. parked cars) and you won't get a meaningful heading out of any of these methods. The map can be very useful for estimating heading, and works pretty well for both static and dynamic objects. 

I also think that if you're using a sufficiently expressive machine learning model to make predictions based on the trajectories, the model can generally learn to "see through" the noise and not overfit too it. There is a lot of training data available.

**Comment by stratomaster31** [comment]
Hi James,

You're right, noise in the training data can be even good for preventing over-fitting. I developed a deep generative model which is not working bad (but far from being a reliable model) and, awaiting for numeric metrics, a qualitative inspection of its results  tells me it is not working better than KNN...

I deeply think that engineers should not rely solely on the brute force part of deep learning , which for instance is taking the whole database, developing a model and taking metrics...  Deep Learning models tend to be very complex and can be hardly interpreted or explained, thus, engineers have to get a deep understanding of the database they are working with. In that sense. I'm pruning different scenarios in your fantastic data-set, and there comes in place the signal processing techniques
