### ISSUE TITLE
Missing stereo baseline in the code

### ISSUE THREAD

**Issue by mileyan** [argoai/argoverse-api#71]
Thanks for your dataset. I have just found the last column of K is zero [Link](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/calibration.py#L92), so self.bx = K[0,3] / (-self.fu) = 0 / (-self.fu) = 0. Would it be possible to fix it?

**Comment by johnwlambert** [comment]
The mathematical formulation is equivalent. We prefer 4x4 matrices for extrinsics over 3x4 in our code in order to utilize a common SE(3) class throughout our codebase.
