### ISSUE TITLE
Missing link in the tracking baseline https://github.com/tracking_baseline

### ISSUE THREAD

**Issue by chowkamlee81** [argoai/argoverse-api#73]
links mentioned https://github.com/tracking_baseline not working

**Comment by James-Hays** [comment]
Where did you see this link? The tracking baseline should be released soon, but that won't be the URL.

**Comment by jagjeet-singh** [comment]
Tracking baseline code is available at
https://github.com/alliecc/argoverse_baselinetracker

**Comment by johnwlambert** [comment]
@chowkamlee81 If you're interested, we welcome submissions to our 3d tracking leaderboard at https://evalai.cloudcv.org/web/challenges/challenge-page/453/leaderboard/1278
