### ISSUE TITLE
Trouble with result submission for forecasting on evalAI

### ISSUE THREAD

**Issue by nitinsinghgit** [argoai/argoverse-api#75]
I am getting the error "You have 0 submissions that are being processed. Please wait for them to finish and then try again" when submitting my results on [https://evalai.cloudcv.org/web/challenges/challenge-page/454/submission]. I used the upload file option and the size of the submission was 26 MB.
![image](https://user-images.githubusercontent.com/9164618/66767991-95068300-ee7f-11e9-92ad-88dfc47206e5.png)

**Comment by jagjeet-singh** [comment]
Eval AI team took care of that. Can you confirm if it's resolved for you?

**Comment by nitinsinghgit** [comment]
Yes, it is resolved.
