### ISSUE TITLE
Usefulness of the dataset for vulnerable road user is limited by the blurred pedestrian faces

### ISSUE THREAD

**Issue by abhishek1411** [argoai/argoverse-api#77]
Hello,
Thank you for the dataset. I am a master student at TU Delft in the faculty of cognitive robotics working on motion forecasting for Vulnerable Road Users. My work requires the extraction of important contextual cues from the image along with the position to predict the future trajectory of pedestrian/cyclist. 
And as such, it would be super helpful if the dataset contained naturalistic driving scenarios without the pedestrian's faces being blurred, as any work with a blurred face in the dataset would induce an artificial bias.
So, is there a possibility of getting the dataset without the faces being blurred?

**Comment by James-Hays** [comment]
Hi Abhishek,

We are definitely sympathetic to this problem. But it's very important to us to protect the privacy of people who might have ended up in our dataset. The blur we used in Argoverse 1.0 was quite strong and blurred faces into the background to the degree that off the shelf object detectors like mask RCNN failed to detect pedestrians. In Argoverse 1.1 we changed the blur a bit to be more spatially constrained but stronger on the face itself in the hope that image-based object detectors work a bit better on pedestrians.

All that said, I don't think there's any possibility of us publicly sharing a dataset with unblurred faces. What type of contextual cues were you considering? I wonder what you can still get with blurry pedestrians. Longer term, we could consider detecting attributes for the pedestrian annotations before they are blurred for release.

**Comment by abhishek1411** [comment]
Hey hi,
I was especially interested in the head orientation and movement of pedestrians for the motion forecasting of pedestrians. And thank you for the Argoverse 1.1 and let me get back to you after running a few detection algorithms for the pedestrian.
