### ISSUE TITLE
Object types in Forecasting dataset

### ISSUE THREAD

**Issue by Elbek1997** [argoai/argoverse-api#79]
I was working with argoverse dataset for vehicle trajectory model.  I hope you can help me.

I need to extract trajectory of individual vehicles. Does Track ID define individual object.

And I need trajectories of vehicles.

On the website it says that dataset includes 15 types of objects. But I have seen only 3 object types:

1. Agent
2. AV
3. OTHERS

Which one is vehicle?

Thank you in advance. Appreciate dataset.

**Comment by sujithvemi** [comment]
AV - Autonomous Vehicle
AGENT - The object with most interesting trajectory or track
OTHERS - Include all the other objects in the scene for which tracks are recorded

The 15 object classes you mention are provided in the 3D tracking dataset. To my knowledge, they haven't made any such statement regarding forecasting dataset.

**Comment by Elbek1997** [comment]
Thank you @sujithvemi . Is AGENT vehicle or not ?

**Comment by sujithvemi** [comment]
> Thank you @sujithvemi . Is AGENT vehicle or not ?

It is.

**Comment by Elbek1997** [comment]
Thanks @sujithvemi I am closing issue

**Comment by duduheihei** [comment]
> AV - Autonomous Vehicle AGENT - The object with most interesting trajectory or track OTHERS - Include all the other objects in the scene for which tracks are recorded
> 
> The 15 object classes you mention are provided in the 3D tracking dataset. To my knowledge, they haven't made any such statement regarding forecasting dataset.

What's the definition of the most interesting  trajectory or track?
