### ISSUE TITLE
ArgoverseMap() error FileNotFoundError

### ISSUE THREAD

**Issue by hongsong-wang** [argoai/argoverse-api#80]
I install argoverse-api, and import is ok.
from argoverse.map_representation.map_api import ArgoverseMap
But, there is a problem with
avm = ArgoverseMap()
It says pruned_argoverse_pit_10314_vector_map.xml is not found. 

![image](https://user-images.githubusercontent.com/5914833/67587674-6df45f00-f765-11e9-85fb-d5b882413b27.png)

Do anybody know how to solve this problem?

**Comment by alliecc** [comment]
Did you download the map from https://s3.amazonaws.com/argoai-argoverse/hd_maps.tar.gz ?

**Comment by hongsong-wang** [comment]
I do not download the map. I will try it. Thanks!
