### ISSUE TITLE
Stereo Image Rectification

### ISSUE THREAD

**Issue by cxy1997** [argoai/argoverse-api#82]
Hi, I found that the stereo images in Argoverse are slightly misaligned. 

I tried to rectify them with 
```python
left_img, right_img = cv2.imread(left_src), cv2.imread(right_src)
R = np.matmul(np.linalg.inv(calibL.R), calibR.R)
T = np.matmul(np.linalg.inv(calibL.R), (calibR.T - calibL.T))
distCoeff = np.zeros(4)

R1, R2, P1, P2, Q, roi1, roi2 = cv2.stereoRectify(
    cameraMatrix1=calibL.K[:3, :3],
    distCoeffs1=distCoeff,
    cameraMatrix2=calibR.K[:3, :3],
    distCoeffs2=distCoeff,
    imageSize=(STEREO_IMG_WIDTH, STEREO_IMG_HEIGHT),
    R=R,
    T=T,
    flags=cv2.CALIB_ZERO_DISPARITY,
    alpha=0
)

map1x, map1y = cv2.initUndistortRectifyMap(
    cameraMatrix=calibL.K[:3, :3],
    distCoeffs=distCoeff,
    R=R1,
    newCameraMatrix=P1,
    size=(STEREO_IMG_WIDTH, STEREO_IMG_HEIGHT),
    m1type=cv2.CV_32FC1)

map2x, map2y = cv2.initUndistortRectifyMap(
    cameraMatrix=calibR.K[:3, :3],
    distCoeffs=distCoeff,
    R=R2,
    newCameraMatrix=P2,
    size=(STEREO_IMG_WIDTH, STEREO_IMG_HEIGHT),
    m1type=cv2.CV_32FC1)

left_img_rect = cv2.remap(left_img, map1x, map1y, cv2.INTER_LINEAR)
right_img_rect = cv2.remap(right_img, map2x, map2y, cv2.INTER_LINEAR)
cv2.imwrite(left_dst, left_img_rect)
cv2.imwrite(right_dst, right_img_rect)
```
The rectified images are still misaligned. 
![rect](https://user-images.githubusercontent.com/15073226/67721248-712d5c00-f9ac-11e9-813c-9ea6fa14e5ab.png)

Have you tried to rectify the images? I'm not sure if my code is wrong or if the calibration parameters are incorrect. Thanks a lot!

**Comment by James-Hays** [comment]
Are you experimenting with Argoverse 1.0 or 1.1 (see https://www.argoverse.org/data.html#download-link )? In version 1.1 we reduced the epipolar alignment error by half.

**Comment by cxy1997** [comment]
Hi @James-Hays, we are using Argoverse 1.1.

**Comment by johnwlambert** [comment]
Hi @cxy1997, I'm looking at the documentation for [initUndistortRectifyMap](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html#void%20initUndistortRectifyMap(InputArray%20cameraMatrix,%20InputArray%20distCoeffs,%20InputArray%20R,%20InputArray%20newCameraMatrix,%20Size%20size,%20int%20m1type,%20OutputArray%20map1,%20OutputArray%20map2)) and it looks like you are computing a joint undistortion and rectification transform. That would be helpful for distorted imagery, but Argoverse imagery has already been undistorted, so that pixel remapping transform won't be right.

**Comment by cxy1997** [comment]
Hi @johnwlambert, I don't think that's the cause of the problem. I have set all distortion parameters to zero so they won't influence the transform.

**Comment by dikpalargo** [comment]
@cxy1997 Can you please check if the T you compute in line 3 in your code snippet is correct? I think it should be T_r - R * T_l

**Comment by johnwlambert** [comment]
@cxy1997 Got it, sounds reasonable then if distortion coefficients are set to zero.

@dikpalargo I'm also concerned about the transformation @cxy1997  calculated between camera frames. [We provide a transformation from the egovehicle frame (center of back axle) to the camera coordinate frame](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/calibration.py#L529) `cam_SE3_egovehicle` that will take
`cam_pt = cam_SE3_egovehicle * p_egovehicle`
I would expect to do something like
`camL_SE3_egovehicle.dot(inv(camR_SE3_egovehicle ))`
to get Right->Left transformation
 I would expect something like:
![IMG_0718 (1)](https://user-images.githubusercontent.com/16724970/67729352-1c4b0f00-f9c7-11e9-9522-f825aa716623.jpg)

**Comment by cxy1997** [comment]
Hi @johnwlambert, great suggestion! 

I recalculated `R` and `T` with
```python
extrinsic = np.dot(calibR.extrinsic, np.linalg.inv(calibL.extrinsic))
R = extrinsic[:3, :3]
T = extrinsic[:3, 3]
```
since `cv2.stereoRectify()` needs Left -> Right transformation matrix

The stereo images are aligned now
![rect](https://user-images.githubusercontent.com/15073226/67730870-ba8da380-f9cc-11e9-8668-bddee28ea407.png)

Thanks so much!

**Comment by johnwlambert** [comment]
No problem @cxy1997, let me know if you run into any other difficulties with the data or API code.

**Comment by lizolson1** [comment]
Hi @johnwlambert, have all of the datasets for 1.1 been updated? The sequences in the first folder (train1) are different between 1.0 and 1.1. For the rest of the training folders, the sequences are the same, and the stereo calibrations appear to be as well. Thanks!

**Comment by alliecc** [comment]
Hi @lizolson1, many of the logs in Argoverse1.1 are updated. Some have updated labels and some have updated stereo calibration, and the logs in train and Val are switched. Please use the new

**Comment by lizolson1** [comment]
Thank you @alliecc!!

**Comment by swdev1202** [comment]
Thank you guys for sharing a great example!
I am fairly new to computer vision and was not understanding the transformation between reference frames, etc. This [video](https://www.youtube.com/watch?v=vlb3P7arbkU) gives an awesome explanation of what @johnwlambert was showing on the paper! :)
