### ISSUE TITLE
Forecasting dataset measurements?

### ISSUE THREAD

**Issue by Elbek1997** [argoai/argoverse-api#83]
Hi. I was using Argoverse Forecasting dataset. I wanted to ask what is the measurements in this dataset (meters, feet, kilometers or miles). I know that there are two reference points in api. One for each city. 

What are the measurement units for these coordinates? 
I suspect that it is not in meters

**Comment by jagjeet-singh** [comment]
Hi Elbek, All the measurements should be in meters. Can I know what made you think otherwise?

**Comment by Elbek1997** [comment]
> Hi Elbek, All the measurements should be in meters. Can I know what made you think otherwise?

Thank you @jagjeet-singh for help. At first I thought that measurements were in meters, but then I tried coordinates with different SRID as GPS coordinates. Then it showed somewhere near Pittsburgh.
Then I had some suspicion.

Long story short, I needed to confirm this for research.

I am closing issue.
