### ISSUE TITLE
The annotate frame rate of the tracking data?

### ISSUE THREAD

**Issue by SpyderXu** [argoai/argoverse-api#87]
What is the annotate frame rate of the tracking data? I did not find it in the paper. Thanks a lot!

**Comment by James-Hays** [comment]
There's no simple answer for that. The annotations are not done at some fixed cadence (e.g. 2hz) and interpolated. But it's not necessarily the case that every cuboid is touched on every frame, either. 

Regardless, the expectation is that every cuboid is reasonable for every frame. So if I had to pick an annotation frame rate, I would say 10hz (the same as the lidar accumulation frame rate).
