### ISSUE TITLE
Code for 3D object tracking?

### ISSUE THREAD

**Issue by sankhanrsss** [argoai/argoverse-api#9]
Any codes(Baseline) have been outsourced  using this dataset has been relesaed? KIndly help

**Comment by James-Hays** [comment]
Hi!

Releasing baselines for tracking and forecasting is on our todo list. But I don't have any concrete ETA. It may be two or three weeks off.

**Comment by ashispapu** [comment]
Any further update on releasing baselines for forecasting and tracking.

**Comment by James-Hays** [comment]
We are still working on it. Glad to see that people are interested!

**Comment by sujithvemi** [comment]
@James-Hays I am trying to look into forecasting as well. Can you please update if there is any ETA?

**Comment by James-Hays** [comment]
September 15th at the latest.

**Comment by yzl96** [comment]
@James-Hays ， hi,  already sep 15th,  very interesting in your baseline.

**Comment by James-Hays** [comment]
Soon, hopefully.

**Comment by jagjeet-singh** [comment]
The tracking baseline code is now available at
https://github.com/alliecc/argoverse_baselinetracker

**Comment by johnwlambert** [comment]
@yzl96 @sujithvemi @sankhanrsss @ashispapu Our 3d tracking evaluation leaderboard is online at https://evalai.cloudcv.org/web/challenges/challenge-page/453/leaderboard/1278, we welcome your entries for the NeurIPS 2019 competition.

**Comment by sujithvemi** [comment]
@jagjeet-singh Thank you for the baseline code.
@johnwlambert Thanks for the invite. Surely will try to participate in forecasting competition.
