### ISSUE TITLE
Mapping agent's location to Driveable Area Matrix 

### ISSUE THREAD

**Issue by stratomaster31** [argoai/argoverse-api#91]
Taking the driveable area (da) matrix show in the figure:

![drivable_area](https://user-images.githubusercontent.com/22171434/69977633-72155880-152b-11ea-8595-2206ba935a66.png)

Following [the supplementary material](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf) I'm trying to map  an agent's (x,y) location to this matrix.

My steps:

1. I assume that x component of agent's location is in x-axis  (columns) of da matrix
2. Since the world-reference system is centered at each, city, in this figure the origin of coordinates is the entry (1522,2264) (row,col) of the matrix.
3. Following 1 and 2, to map agnet's (x,y) to matrix:

       agent_row = (n_rows - floor(y)) + 1522 
       agent_col = floor(x) + 2264 

I'm not getting satisfactory results, so some of my assumptions are wrong...

**Comment by stratomaster31** [comment]
I realized that the API returns the necessary transformation matrix, so, with the following code I think I'm getting the correct results, am I righ?

```
agent_location = observed_agent_trajectory[obs_T]
city = 'MIA'
roi_map, se2_transform = avm.get_rasterized_roi(city) 

homogeneous_pts = np.hstack([agent_location, np.ones((1))]) 
transformed_points = homogeneous_pts.dot(se2_transform.T)
transformed_points = transformed_point_cloud[:2]

agent_col,agent_row = int(transformed_points[0]), int(transformed_points[1])
```

**Comment by Redaimao** [comment]
Hi @stratomaster31 ,
I also have this problem. I tried the way you provided, but still not working.
I wonder what is the coordinate system used in both HD map (drivable area map),
and the motion forecasting annotation (x, y)?
Would you mind giving more detail?
Thank you

**Comment by johnwlambert** [comment]
Hi @Redaimao , thank you for your interest in our work.

Please refer to our README ["A Note Regarding Coordinate Transforms"](https://github.com/argoai/argoverse-api#a-note-regarding-coordinate-transforms"): 

> What about tracks in the forecasting dataset? These are provided directly in the city reference frame (i.e. the map coordinate system).

Any map elements (driveable area, lane centerlines, hallucinated lane polygons) are provided in the city coordinate system. If you haven't had a chance to read it yet, I think Section 1 of our Supplementary Material [(linked here)](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf) would help clarify things a bit.

You can just pass a `meshgrid` of points living in the city frame into the [following API function](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_api.py#L424) to determine if each one lies within the driveable area or not:
```
from argoverse.map_representation.map_api import ArgoverseMap
avm = ArgoverseMap
is_driveable_area = avm.get_raster_layer_points_boolean(
     point_cloud,
     city_name,
     layer_name=""driveable_area"
)
```

**Comment by Redaimao** [comment]
Hi @johnwlambert ,
Thanks for your instruction and reply!

Regards.
