### ISSUE TITLE
Can you provide the actual evaluation code used in the competition?

### ISSUE THREAD

**Issue by joshi-bharat** [argoai/argoverse-api#92]
Hi,

I am working on a project involving 3D tracking using images only. I wanted to use Argoverse Dataset. The evaluation code provided is not enough to calculate errors in case of different ID's. Can you provide the evaluation code used in the competition?
@James-Hays 

Thanks,

**Comment by janesjanes** [comment]
The evaluation code used in the competition is pulling directly from this repo. We plan to update it soon to make it easier to use, but right now for running multiple log Id you can simply call this function https://github.com/argoai/argoverse-api/blob/652bb500eafd2b21a8a346a3b762c1114f4c314a/argoverse/evaluation/eval_tracking.py#L104 with list of multiple paths.
