### ISSUE TITLE
coordinates of forecasting data

### ISSUE THREAD

**Issue by miranheo** [argoai/argoverse-api#93]
![image](https://user-images.githubusercontent.com/24949098/70118443-58028400-16ab-11ea-88ae-70a3ed9cda46.png)

above map is made by map api, render_city_centerlines('MIA')
and the coordinates information (red dot) is provided from the original source.
from forecasting sample data,  especially '2645.csv' file, the last observed coordinates of AGENT is
(x = 417.0737706629 , y = 1161.0730596805)
I want to confirm that the exact location of AGENT on local area.
I wonder why the AGENT (blue dot)  is not on the drive-able area (grey)

thank you!

**Comment by jagjeet-singh** [comment]
Hi @miranheo, Thank you for your interest in Argoverse. I looked into the sequence you mentioned but I'm not able to reproduce the issue.
![image](https://user-images.githubusercontent.com/11771909/70450168-41747800-1a71-11ea-9e38-b2ffe731608d.png)

**Comment by miranheo** [comment]
@jagjeet-singh It was my mistake. Sorry for the confusion.
