### ISSUE TITLE
Differentiating pedestrians from vehicles in the motion forecasting dataset

### ISSUE THREAD

**Issue by Kishaan** [argoai/argoverse-api#94]
HI, 

I looked into the motion forecasting dataset and used the api to visualize the trajectories on the map. I would like to know if there is any way to differentiate between pedestrians and vehicles in the forecasting benchmark. 

The column OBJECT_TYPE tells us about the type of instances in the sequence. In a given sequence, only one AV (ego vehicle) object type, one AGENT (instance for which we predict the trajectory, mostly vehicle), and several OTHERS (all other instances in the scene) are mentioned. Is there any way to differentiate vehicles and pedestrians in this OTHERS category?

**Comment by jagjeet-singh** [comment]
Hi, Unfortunately, the dataset does not provide that differentiation right now.

**Comment by James-Hays** [comment]
Kishaan,

One of the winners of the Argoverse motion forecasting competition used heuristics (map based and velocity based, I imagine) to differentiate between pedestrians and vehicles. That was team uulm-mrm on our leaderboard https://evalai.cloudcv.org/web/challenges/challenge-page/454/leaderboard/1279 

You can see me briefly discussing their method in the video from the NeurIPS 2019 workshop: https://slideslive.com/38922111/machine-learning-for-autonomous-driving-2 at around 1:12 on the timeline. But I don't have the full details on how they did their heuristic filtering.

**Comment by Kishaan** [comment]
HI, 

Thank you for the information. I was looking for a dataset specifically for pedestrian and cyclists trajectory prediction task. Even if I use such heuristics to filter as you mentioned, I doubt the goodness of the classes for the identified entities. It would be much helpful if you could provide the classes for the "OTHERS" category in future releases.
