### ISSUE TITLE
WGS84 coordinates of city origin

### ISSUE THREAD

**Issue by harishrithish7** [argoai/argoverse-api#95]
In your supplementary, you have mentioned 

> The model of the world that we subscribe to within our map and dataset is a local tangent plane centered at a central point located within each city.

What is the WGS84 coordinates of this central point, for Miami and Pittsburgh?

**Comment by johnwlambert** [comment]
Hi @harishrithish7 , In Appendix A.1 of the [Arxiv version](https://arxiv.org/abs/1911.02620), we have the UTM:

*In Pittsburgh, our city origin lies at 583710.0070 Easting, 4477259.9999 Northing in UTM Zone 17. In Miami, our city origin lies at 580560.0088 Easting, 2850959.9999 Northing in UTM Zone 17.*

An [online converter](http://www.rcn.montana.edu/resources/converter.aspx) tells me the corresponding WGSS84 is around:
Pittsburgh (40.44177903050335,-80.01294377278833) for (lat,long)
Miami: (25.774525799252665,-80.19656914436197)

**Comment by harishrithish7** [comment]
Hi @johnwlambert ,

I missed that part. Thank you for the answer.
