### ISSUE TITLE
Question about lane segment.

### ISSUE THREAD

**Issue by sanmin0312** [argoai/argoverse-api#99]
Hello,

I want to ask that the number of points of a centerline in one lane segment is fixed? I only tried with samples, there are all 9 points in one lane segment. and also want to ask about what's the meaning of nan in the centerline point and how could there are no centerline points?

For the last question, is the Argoverse dataset has no information on traffic signals?

**Comment by mpourkeshavarz** [comment]
@sanmin0312 
did you find out if the number of points of a centerline in one lane segment is fixed or not? and the meaning of nan in the centerline point and how could there are no centerline points?

Thanks,
Mozhgan
